README.md

- Noticed the badge was missing, personally find it useful.

Add travis build status to ex_doc readme.md

---

lib/mix/tasks/docs.ex

updated documentation for :readme option

---

README.md

Update README.md to 0.7 version

---

LICENSE
lib/ex_doc/formatter/html/templates/css/elixir.css
lib/ex_doc/formatter/html/templates/css/style.css
lib/ex_doc/formatter/html/templates/js/full_list.js

* Add Style for inline code: This has been an annoyance while reading code, since it was not being highlighted.
* I have updated all the licenses, please let me know if you see one that needs to be included.
* Search box was not being updated when for example you pasted a term

Various fixes: Inline Code + Licenses + Search box

---

mix.exs
mix.lock

I just saw thie PR https://github.com/elixir-lang/elixir/pull/3297 . But the root cause is this issue https://github.com/pragdave/earmark/issues/13, which has been fixed. So, let's update earmark to fix this :)

update earmark to fix some doc format

---

lib/ex_doc/formatter/html.ex

Reference: elixir-lang/ex_doc#215

Delete output directory before generate docs.

---

lib/ex_doc/formatter/html/templates/css/style.css
lib/ex_doc/formatter/html/templates/js/app.js

Use an icon for external links. Fix #189

Add icon to identify external links

---

lib/ex_doc/formatter/html/templates/js/app.js
lib/ex_doc/formatter/html/templates/sidebar_template.eex

This PR fix some issues mentioned by @eksperimental in #232, specifically 1, 4 and 5.

Fix some issues with the sidebar menu

---

lib/ex_doc/formatter/html.ex
lib/ex_doc/formatter/html/templates.ex
lib/ex_doc/formatter/html/templates/module_template.eex
lib/ex_doc/formatter/html/templates/overview_template.eex
lib/ex_doc/formatter/html/templates/readme_template.eex
lib/ex_doc/formatter/html/templates/sidebar_template.eex
test/ex_doc/formatter/html/templates_test.exs

Disable nav link when module type list is empty

---

lib/ex_doc/formatter/html/templates/js/app.js

Recover both features from the old ExDoc version.

Improve events when ESC or ENTER keys are pressed

---

lib/ex_doc/formatter/html/templates/css/style.css

Increase Margins

---

lib/ex_doc/formatter/html/templates/js/app.js

This is known as JS Hoisting, more details:
http://www.adequatelygood.com/JavaScript-Scoping-and-Hoisting.html

Avoid to use a function before its definition

---

test/ex_doc/formatter/html_test.exs

* docs/ renamed to doc/ to follow elixir convention

Do not create doc test folder out of /test/tmp

---

lib/ex_doc.ex
lib/ex_doc/formatter/html/templates.ex
lib/ex_doc/formatter/html/templates/footer_template.eex

Sort alphabetically long lists of options,
Indent mix.exs for easier reading.

Tidy up a few files

---

.gitignore

Sorted alphabetically,
first dirs then files.

.gitignore: sort alphabetically + npm-debug.log

---

test/ex_doc/formatter/html_test.exs

just to check we are redirecting to the proper reame.html page
https://github.com/elixir-lang/ex_doc/issues/297

Test sets main as "readme"

---

lib/ex_doc.ex
lib/ex_doc/cli.ex
lib/ex_doc/formatter/html.ex
lib/ex_doc/formatter/html/templates.ex
lib/ex_doc/formatter/html/templates/sidebar_template.eex

/cc @Dignifiedquire @josevalim
Closes #330

Add logo support

---

lib/ex_doc/formatter/html.ex
lib/ex_doc/formatter/html/templates.ex
lib/ex_doc/formatter/html/templates/module_template.eex
lib/ex_doc/formatter/html/templates/not_found_template.eex
lib/ex_doc/formatter/html/templates/overview_template.eex
lib/ex_doc/formatter/html/templates/readme_template.eex
lib/ex_doc/formatter/html/templates/sidebar_template.eex
test/ex_doc/formatter/html/templates_test.exs

Remove has_readme variables from templates

---

mix.exs
test/ex_doc/formatter/html_test.exs

Closes https://github.com/elixir-lang/ex_doc/issues/368

Suffix dev version

---

lib/ex_doc/retriever.ex

Make "View Source" to show actual definition

---

package.json

This proposal automatically install pre-commit hooks, only apply for the JS/CSS part. Task that we run on each pre-commit:
* Verify the quality of the JS code
* Run some tests
* Prepare the distribution (or minified) files
Closes #268 
/cc @Dignifiedquire

Add pre-commit checks

---

lib/ex_doc/formatter/html/templates/sidebar_template.eex

[sidebar] Do not show empty sections

---

lib/ex_doc/formatter/html/templates/summary_item_template.eex

fixes broken links to types
http://elixir-lang.org/docs/master/elixir/String.html#summary_details

Fix broken internal link: Summary > types

---

lib/ex_doc.ex
lib/ex_doc/cli.ex
lib/ex_doc/formatter/html/templates/sidebar_template.eex
lib/mix/tasks/docs.ex
test/ex_doc/cli_test.exs

This PR try to fix [this](https://github.com/elixir-lang/ex_doc/pull/462#issuecomment-154483172)

Allow user define title for additional pages

---

lib/ex_doc/markdown/cmark.ex
mix.exs
mix.lock
test/ex_doc/markdown/cmark_test.exs
test/test_helper.exs

Note that I'm not sure if it's appropriate to do this or create something external, but it's simple enough so here we are.
This is basically an edited copy-pasta of the `ExDoc.Markdown.Earmark` module.  I'm new to elixir so please accept my apologies if I did anything senseless here.

Add support for cmark.ex markdown processing.

---

lib/ex_doc/retriever.ex
test/ex_doc/retriever_test.exs
test/fixtures/multiple_specs.ex

Sort specs by line to preserve ordering

---

assets/js/sidebar.js

Fixes js linting errors to fix the build

Fix sidebar js lint errors

---

test/ex_doc/retriever_test.exs
test/fixtures/callbacks_no_docs.ex

The issue #447 does not appear to be broken anymore and could be closed.
A test is included in this PR to verify this is fixed in case you would like to include a test for this.
Fixes #447

Verify callbacks with no docs included

---

lib/ex_doc/formatter/html.ex
test/ex_doc/formatter/html_test.exs

WIP: Keep track of generated files

---

lib/ex_doc/formatter/html.ex
lib/ex_doc/retriever.ex

Add atom module name to list for doc generation

---

lib/ex_doc/formatter/epub.ex
lib/ex_doc/formatter/epub/templates.ex
lib/ex_doc/formatter/epub/templates/content_template.eex
lib/ex_doc/formatter/epub/templates/extra_template.eex
lib/ex_doc/formatter/epub/templates/nav_template.eex
lib/ex_doc/formatter/epub/templates/toc_template.eex
lib/ex_doc/formatter/html.ex
test/ex_doc/formatter/epub_test.exs

Better support for extra content (EPUB format)

---

.gitignore
lib/ex_doc/retriever.ex
lib/mix/tasks/docs.ex
test/fixtures/umbrella/apps/bar/lib/bar.ex
test/fixtures/umbrella/apps/bar/mix.exs
test/fixtures/umbrella/apps/foo/lib/foo.ex
test/fixtures/umbrella/apps/foo/mix.exs
test/fixtures/umbrella/mix.exs
test/mix/tasks/docs_test.exs

Fixes #567
Looking forward to hearing feedback about implementation, I'll add tests afterwards.
Demo using this branch: http://wojtekmach.pl/acme_bank_docs/main.html

Generate top-level docs for an umbrella project

---

lib/ex_doc/formatter/epub.ex

* Reduce the number of args required in some functions.
* Fix references to assets in the OPF manifest.
* Compress JS files when creating ZIP
Fixes #619

Fix missing assets in the header section

---

lib/ex_doc/formatter/epub.ex
lib/ex_doc/formatter/epub/templates/extra_template.eex

For more information please see [this comment](https://github.com/phoenixframework/phoenix_guides/issues/623#issuecomment-261424213)
/cc @wsmoak @josevalim

EPUB format: Fix errors reported by @wsmoak

---

.travis.yml

Borrowed from [ecto](https://github.com/elixir-ecto/ecto/blob/master/.travis.yml#L9-L14).

Limit Travis build matrix to oldest/newest pairs

---

lib/ex_doc/retriever.ex

corrects find_actual_line/3 error.

---

lib/ex_doc/retriever.ex
test/ex_doc/formatter/html/templates_test.exs

Annotate opaque types

---

CHANGELOG.md
mix.exs

also fix typo in CHANGELOG.md (missing backtick)

add changelog doc page

---

lib/ex_doc/formatter/html/autolink.ex
test/ex_doc/formatter/html/autolink_test.exs

Autolink Hex docs

---

lib/ex_doc/formatter/html/autolink.ex
test/ex_doc/formatter/html/autolink_test.exs

Screenshot:
Although maybe it's taking this too far :)

Autolink `mix help TASK`

---

lib/ex_doc/markdown/earmark.ex
test/ex_doc/markdown/earmark_test.exs

Disable earmark smartypants option by default

---

lib/ex_doc/formatter/html/templates.ex
test/ex_doc/formatter/html/templates_test.exs

Keep trailing periods in summaries

---

lib/ex_doc/formatter/html/templates.ex
lib/ex_doc/retriever.ex
test/ex_doc/formatter/html_test.exs
test/ex_doc/retriever_test.exs

Add "mix " to Mix tasks

---

.travis.yml

Just experimenting, ignore me unless this works beautifully 😄

Try out stages in Travis

---

lib/ex_doc/formatter/html/autolink.ex
test/ex_doc/formatter/html/autolink_test.exs

Encode URL fragments with a specific function

---

lib/ex_doc/formatter/html/autolink.ex
test/ex_doc/formatter/html/autolink_test.exs

This addresses #1079.
Since @eksperimental refactored a lot of this code not too long ago, I wanted to PR this WIP to check if I'm following the imagined structure or implemented a completely off-track solution.
Things that are currently missing:
- ~~Supporting multiple arities for built-in types and kernel functions~~
- Any additional work that is needed for making this work on epubs(?)

Support autolinking for multiple arities

---

lib/ex_doc/formatter/html/autolink.ex
test/ex_doc/formatter/html/autolink_test.exs

Change autolink placeholder to something less likely

---

lib/ex_doc/config.ex
lib/mix/tasks/docs.ex
test/mix/tasks/docs_test.exs

Adds epub to the default formatters

---

README.md
lib/ex_doc/autolink.ex
lib/ex_doc/formatter/html.ex
test/ex_doc/autolink_test.exs

Auto-link to extras

---

.gitignore
.travis.yml
assets/README.md
assets/package-lock.json
assets/package.json
assets/webpack.js
mix.exs

Move package.json and friends to their home

Move front end configuration to assets/

---

.travis.yml

Please refer to https://github.com/dashbitco/broadway/pull/188 for justification.

add more Elixir and Erlang/OTP combinations to CI

---

.travis.yml

test that the docs for ExDoc are generated.

Add stage in CI: build docs

---

assets/js/keyboard-shortcuts.js

Using KeyboardEvent.key with fallback to keydown.keyCode.
Fix #1198
Fix #997

Fix keyboard shortcuts on non US keyboard layouts

---

assets/less/content/general.less
assets/less/html.less
assets/less/makeup.less
assets/less/night/content/footer.less
assets/less/night/content/general.less
assets/less/night/quick-switch.less
assets/less/night/search.less
assets/less/variables/common.less
assets/less/variables/elixir.less

Font colors have been updated to have enough contrast in day-mode and night-mode,
according to the suggestions by https://github.com/Khan/tota11y
**A) Daymode, with errors**
**A) Daymode,  original**
**A) Daymode, fixed**
**************
**B) Daymode, with errors**
**B) Daymode, original**
**B) Daymode, fixed**
***********
**C) Daymode, with errors**
**C) Daymode, original**
**C) Daymode, fixed**
************
**D) Daymode, with errors**
**D) Daymode, original**
**D) Daymode, fixed**
**************
**E) Nightmode, with errors**
**E) Nightmode, original**
**E) Nightmode, fixed**
**********
**F) Nightmode, with errors**
**F) Nightmode, original**
**F) Nightmode, fixed**

Accessibility: Improve font color contrast

---

assets/test/tooltips/hints-extraction.spec.js
lib/ex_doc/formatter/epub/templates/module_template.eex
lib/ex_doc/formatter/html/templates.ex
lib/ex_doc/formatter/html/templates/detail_template.eex
lib/ex_doc/formatter/html/templates/module_template.eex
lib/ex_doc/formatter/html/templates/summary_entry_template.eex
lib/ex_doc/formatter/html/templates/summary_template.eex
test/ex_doc/formatter/epub/templates_test.exs
test/ex_doc/formatter/html/templates_test.exs
test/ex_doc/formatter/html_test.exs

Remove use of sr-only class and elements

Add aria-label and title attributes to links

---

lib/ex_doc/autolink.ex
test/ex_doc/autolink_test.exs

Indent spec after line break

---

lib/ex_doc/autolink.ex
test/ex_doc/autolink_test.exs

Reverts elixir-lang/ex_doc#1296

Revert "Indent spec after line break"

---

CHANGELOG.md
lib/ex_doc/formatter/html/templates.ex
lib/ex_doc/utils/simple_json.ex
lib/mix/tasks/docs.ex
mix.exs

List of changes:
- Use common source url
- Fix typos
- Add changelog link to hex info page

Misc doc changes

---

lib/ex_doc/autolink.ex
lib/ex_doc/formatter/html.ex
lib/ex_doc/markdown/earmark.ex
lib/ex_doc/retriever.ex
test/ex_doc/autolink_test.exs
test/ex_doc/formatter/html_test.exs
test/ex_doc/markdown/earmark_test.exs
test/ex_doc/retriever_test.exs
test/fixtures/README.md

Add metadata to ast and fix HTML escaping

---

lib/ex_doc/retriever.ex
test/ex_doc/retriever_test.exs
test/test_helper.exs

I've also added some TODOs, I want to address some as part of the PR and others down the road.

Rewrite retriever tests to not rely on fixtures

---

lib/ex_doc.ex
lib/ex_doc/cli.ex
lib/ex_doc/formatter/html/templates/head_template.eex

This is cherry-picked from #1291 with minor modifications.
Co-authored-by: Radek Szymczyszyn <radoslaw.szymczyszyn@erlang-solutions.com>
Co-authored-by: Wojtek Mach <wojtek@wojtekmach.pl>

Add --proglang flag

---

assets/js/handlebars/template-helpers/isLocal.js
assets/less/content/footer.less
lib/ex_doc/formatter/html.ex
lib/ex_doc/formatter/html/templates.ex
lib/ex_doc/formatter/html/templates/module_entry_template.eex
test/ex_doc/formatter/html_test.exs

Add function landing page

---

lib/ex_doc/formatter/html.ex
lib/ex_doc/formatter/html/search_items.ex
test/ex_doc/formatter/html_test.exs

Adding spaces on paragraph endings for search results

---

lib/ex_doc/autolink.ex
test/ex_doc/autolink_test.exs
test/ex_doc/formatter/html/templates_test.exs

Closes https://github.com/elixir-lang/ex_doc/issues/1322

Deal with custom link that links to undefined/hidden module

---

lib/ex_doc.ex

Hey!
I was just trying the current master on some Erlang projects and found this tiny issue. Works like a charm with this fix 🎉

Handle --proglang string

---

lib/ex_doc/language/elixir.ex
lib/ex_doc/language/erlang.ex
test/ex_doc/language/elixir_test.exs
test/ex_doc/language/erlang_test.exs

Demo:
http://wojtekmach.pl/docs/telemetry/telemetry.html#execute/3

ExDoc.Language.Erlang: Autolink typespecs

---

README.md
lib/ex_doc/application.ex
lib/ex_doc/shell_lexer.ex

Add simple shell lexer

---

assets/js/copy-button.js
assets/less/copy-button.less
assets/less/html.less
assets/less/night/copy-button.less

- Fix SVG color in night mode
- Adjust green color to match the color used in syntax highlight
- Fix timeout issue when clicking the copy button multiple times

Fix copy button in night mode

---

assets/js/handlebars/templates/modal-layout.handlebars
assets/js/modal.js
assets/js/settings.js
assets/less/modal.less

Closes https://github.com/elixir-lang/ex_doc/issues/1438
While implementing I noticed that a lot of buttons/links in ex_doc lack proper focus styling. Should this be another issue?

Implement focus trapping on modals

---

assets/less/autocomplete.less
assets/less/content/general.less
assets/less/night/content/general.less

Changes the autocomplete background to match the new palette
Fixes the color of the settings icon in both modes

Small fixes

---

assets/js/handlebars/templates/settings-modal-body.handlebars
assets/less/keyboard-shortcuts.less
assets/less/modal.less
assets/less/settings.less

Some small improvements on modal/settings component:
| Before | After |
| --------------- | --------------- |
| <img width="271" alt="image" src="https://user-images.githubusercontent.com/464900/148964249-f4b3080c-e271-4552-bded-c1bd340212a0.png"> | <img width="270" alt="image" src="https://user-images.githubusercontent.com/464900/148964280-0083618b-1df0-4825-8c51-909d2f71c45e.png"> |
| <img width="271" alt="image" src="https://user-images.githubusercontent.com/464900/148964601-0cf5a9c1-f049-456e-bbb2-588f3d0a99a9.png"> |  <img width="270" alt="image" src="https://user-images.githubusercontent.com/464900/148964644-85f64297-3d30-4d33-8519-12d74ce76f57.png"> |

Update modal and settings styles for small viewport

---

assets/js/handlebars/templates/settings-modal-body.handlebars

This PR fixes some grammar mistakes in the Settings modal.

Fix grammar in the settings modal

---

assets/js/autocomplete/suggestions.js
assets/test/autocomplete/suggestions.spec.js

https://github.com/elixir-lang/ex_doc/issues/1518
add extra node in autocomplete

include page titles in autocomplete

---

assets/js/theme.js
assets/js/toast.js
assets/less/html.less
assets/less/night/toast.less
assets/less/toast.less
lib/ex_doc/formatter/html/templates/sidebar_template.eex

[at José's suggestion](https://github.com/elixir-lang/ex_doc/pull/1532#issuecomment-1088805331)
- Add a new toast mechanism. vanilla js
- make the toast theme-aware and reduced-motion-aware.
- toast should be accessible, inasmuch as I know how.
- when browser changes themes automatically and while on the system theme, toast a message
- when user changes themes via keyboard shortcut, toast a message
Demo:
https://user-images.githubusercontent.com/643967/161885179-17abc6de-6fc6-44c3-a5af-2b55529a1f30.mov

Add toast when changing theme via keyboard

---

test/ex_doc/formatter/html_test.exs

Related PR: https://github.com/elixir-lang/ex_doc/pull/1553
/cc @timothyvanderaerden

Add tests for license files and all files in .build

---

test/ex_doc/formatter/html/templates_test.exs

A continuation of https://github.com/elixir-lang/ex_doc/pull/1557

Use tmp_dir in template tests

---

assets/js/quick-switch.js

Change minimal package search length to 2

---

lib/ex_doc/language/elixir.ex
test/ex_doc/retriever_test.exs

Remove line from every signature meta

---

assets/less/layout.less

Details in commit message. Tested in WebKit and Gecko, desktop and mobile.

Prevent sidebar button scrolling out of view

---

assets/css/custom-props/theme-dark.css
assets/css/custom-props/theme-light.css
assets/css/quick-switch.css
assets/js/handlebars/templates/quick-switch-modal-body.handlebars
lib/mix/tasks/docs.ex

Adjust quick switch in night mode

---

lib/ex_doc/utils.ex
test/ex_doc/utils_test.exs

Add Elixir special punctuation ! and ? to natural sort

---

assets/css/content/code.css

Add scrollbar to large output code blocks

---

assets/css/content/code.css
assets/css/custom-props/theme-dark.css
assets/css/custom-props/theme-light.css

Add night version of the output scrollbar

---

assets/css/content/functions.css
assets/js/handlebars/templates/tooltip-body.handlebars

Reverts elixir-lang/ex_doc#1640

Revert "Change format for tooltip header"

---

assets/css/_html.css
assets/css/content/cheatsheet.css
assets/css/content/code.css
assets/css/custom-props/common.css
assets/css/layout.css
assets/css/print-cheatsheet.css
assets/css/print.css
assets/css/sidebar.css

Capitalisation, leading 0, colour syntax, etc.

Tweak CSS for consistency

---

assets/css/sidebar.css
assets/js/autocomplete/suggestions.js
assets/js/keyboard-shortcuts.js
assets/test/autocomplete/suggestions.spec.js

Suggestions implemented from #1636:
* Prevent lost keystrokes when focusing search input using a keyboard shortcut (`/` or `s`)
* Include page and module sections in search suggestions
* Increase click-target of sidebar links and add hover states

UX improvements

---

lib/ex_doc/language/elixir.ex
test/ex_doc/language/elixir_test.exs

Don't attempt parsing code blocks that don't look like modules

---

assets/css/sidebar.css

[Reported here](https://github.com/elixir-lang/ex_doc/pull/1652#issuecomment-1519134546) (cc @stefanchrobot)

Fix text overflow ellipses in sidebar

---

assets/css/content/general.css
assets/css/custom-props/theme-dark.css
assets/css/custom-props/theme-light.css

Weaken tone of content link underlining to improve legibility of link text

---

assets/js/tabsets.js

Mostly code commenting.
Sorry for failing to get this in before the merge. :)

Tidy up tabsets JavaScript

---

README.md

Color theme is only evaluated on (re)load. I don't see an easy way to hook into the (minified) SettingsStore.

mermaid.js to 10.2.3 (async invocation) and make it respect color theme

---

README.md

Run render asynchronously to enable processing all diagrams in parallel.
Sorry to bother you again, I forgot this is not Elixir.  💚
Amends #1723.

mermaid.js proper async processing

---

assets/css/content/functions.css
assets/css/settings.css

Fixes the two remaining issues from https://github.com/elixir-lang/ex_doc/pull/1749#issuecomment-1685354442

Improve keyboard navigation follow up

---

lib/ex_doc/formatter/html/templates/sidebar_template.eex
test/ex_doc/formatter/html/templates_test.exs

A follow up to https://github.com/elixir-lang/ex_doc/pull/1760

Fix tabpanel role invalid on a list element

---

assets/css/sidebar.css
lib/ex_doc/formatter/html/templates/sidebar_template.eex
test/ex_doc/formatter/html/templates_test.exs

Fix sidebar overflow-y behavior

---

lib/ex_doc/application.ex
lib/ex_doc/autolink.ex
test/ex_doc/formatter/html_test.exs
test/ex_doc/language/elixir_test.exs
test/ex_doc/language/erlang_test.exs

This is the first step towards having more async tests.

Limit CaptureIO usage in tests

---

lib/ex_doc/formatter/html/templates/extra_template.eex
lib/ex_doc/formatter/html/templates/head_template.eex
lib/ex_doc/formatter/html/templates/module_template.eex
lib/ex_doc/formatter/html/templates/not_found_template.eex
lib/ex_doc/formatter/html/templates/search_template.eex

@josevalim As discussed in https://github.com/hexpm/hexdocs/issues/36#issuecomment-1806407623 
Couldn't find any related test coverage I could hook into, please let me know if tests are needed!

Add noindex meta tag to 404 and Search pages

---

lib/ex_doc/autolink.ex
test/ex_doc/language/elixir_test.exs

Fixes https://github.com/elixir-lang/elixir/issues/13315

Autolink .cheatmd files

---

assets/js/entry/html.js
assets/js/helpers.js
assets/js/keyboard-shortcuts.js
assets/js/os.js
assets/js/search-bar.js
assets/js/styling.js

There were previously two functions that checked for Apple OS.
Converts previous OS module to Styling and modernises the function in Helpers.

Consolidate Apple OS detection

---

lib/ex_doc/formatter/html/templates/detail_template.eex
test/ex_doc/formatter/html/templates_test.exs

Fixes #1935.
I thought it would be more work, but this seems to be all that's required.

Switch anchor `title` to `aria-label`

---

README.md

Sorry for the delay - I wanted to test them first. Addresses #1941

Update examples in Extensions section

---

assets/js/sidebar/sidebar-list.js

Fixes https://github.com/elixir-lang/ex_doc/pull/2007#issuecomment-2576106963

Close open menus on nav

---

assets/css/content/bottom-actions.css

Improve the layout of bottom actions by adding spacing and hover effects for better user experience.

Enhance bottom actions layout with improved spacing, hover effects, and text alignement

---

assets/css/copy-button.css

Enhance the copy button's appearance and usability by adjusting its positioning, padding, and border properties.
this should help separate it from the code
focus state before
after

Improve copy button styling for better visibility and interaction

---

assets/css/tabset.css

Improve the visual layout of the tabset by adjusting padding, borders, and shadows for better consistency and user experience.
this implementation should solve all issues without any compromises and blends naturally with the theme. inspired by https://vitepress-plugins.sapphi.red/tabs/
https://docusaurus.io/docs/markdown-features/tabs
by far i think it looks the cleanest and most professional

Enhance tabset styles for improved layout and visual consistency

---

assets/css/content/functions.css

Now the animation transitions back to the initial state instead of stopping suddently

Refactor blink-background animation keyframes for clarity

---

assets/css/custom-props/common.css

Improve typography consistency by updating and reordering default font families.

Update fallback fonts for typography consistency

---

assets/css/autocomplete.css
assets/css/content/code.css
assets/css/content/footer.css
assets/css/content/functions.css
assets/css/content/general.css
assets/css/copy-button.css
assets/css/custom-props/common.css
assets/css/keyboard-shortcuts.css
assets/css/layout.css
assets/css/search-bar.css
assets/css/settings.css
assets/css/sidebar.css

Consistently apply CSS variables for [font sizes](https://v3.tailwindcss.com/docs/font-size) across the application to enhance maintainability and ensure a unified design.
No size changes applied, custom values remain.

Refactor font sizes to use CSS variables for consistency

---

lib/ex_doc/language/elixir.ex

This fixes the small typespec issue mentioned in issue #2117

This fixes issue #2117

---

assets/css/sidebar.css

move external link margin to the left
