lib/ex_doc/formatter/html/templates/index_template.eex, mix.lock
I noticed in the elixir website, when trying to link to a page in the docs, the frames are missing.
well, this solves this issue.
Let's say you want to link to: 
http://eksperimental.github.io/elixir/doc/Kernel.SpecialForms.html
then if you want to load the frames you link to:
http://eksperimental.github.io/elixir/doc//#!Kernel.SpecialForms.html
or even to special function in particular
http://eksperimental.github.io/elixir/doc/#!Kernel.SpecialForms.html#__DIR__/0
Let's say you are running the file in your computer, so you have to call `index.html`
http://eksperimental.github.io/elixir/doc/index.html#!Kernel.SpecialForms.html#__DIR__/0
it does still work.
Too bad I cannot update the url when you click, (so you can directly copy the url from the address bar) this is due to security …
=> Link to pages and load frame

lib/ex_doc/retriever.ex, test/ex_doc/retriever_test.exs
`Error` is used directly in ExDoc.Retriever, which will raise and error.
=> fix `Error is not available` error in Retriever

lib/ex_doc/formatter/html/templates/index_template.eex, lib/ex_doc/formatter/html/templates/list_template.eex, lib/ex_doc/formatter/html/templates/module_template.eex, lib/ex_doc/formatter/html/templates/overview_template.eex, lib/ex_doc/formatter/html/templates/readme_template.eex
This PR include some improvements related with the markup, according to the specification for HTML5:
* The `type` attribute for the `script` element by default is `text/javascript` and now is optional.
* The `type` attribute for the `style` element by default is `text/css`, also the `charset` parameter must not be specified.
* Exactly one of the `name`, `http-equiv`, and `charset` attributes must be specified in the `meta` element.
* If either `name` or `http-equiv` is specified, then the `content` attribute must also be specified. Otherwise, it must be omitted.
I also put the scripts at the bottom of the page to avoid blocking parallel downloads, this might improve the overall rendering time. Finally, jQuery now can be obtained from a _Content Delivery Network_, if this fails we can …
=> Fixed HTML5 markup validation errors.

.travis.yml, lib/ex_doc/markdown/hoedown.ex, lib/ex_doc/markdown/pandoc.ex, lib/ex_doc/retriever.ex
Changes proposed by @dignifiedquire in his `design` branch.
=> Added the :fenced_code Hoedown option.

lib/ex_doc/formatter/html.ex, lib/ex_doc/markdown.ex, lib/ex_doc/markdown/hoedown.ex, lib/ex_doc/markdown/pandoc.ex, test/ex_doc/formatter/html_test.exs, test/ex_doc/markdown/hoedown_test.exs, test/ex_doc/markdown/pandoc_test.exs
This commit includes the following:
* Improve `pretty_codeblocks` function to work with Hoedown and Pandoc
* Add more tests for `pretty_codeblocks`
* Delete duplicate code in `ExDoc.Markdown.to_html`
This is a possible fix for #214
=> Handle code blocks with and without language spec

lib/ex_doc.ex, lib/ex_doc/formatter/html.ex, lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/formatter/html/templates/overview_template.eex, lib/ex_doc/formatter/html/templates/sidebar_template.eex
Now we consider the following cases:
* `--main` and `--readme` options are set: `--main` is `index.html`
* `--main` is not set and `--readme` option is set: `--readme` is `index.html`
* `--main` and `--readme` options are not set: Overview is `index.html`
@josevalim Please let me know if this fulfil your request. 
Fix: #221
=> Index priority: Main -> README -> Overview

lib/ex_doc/formatter/html/templates/js/app.js
Right now if there are no nodes (protocols, modules or exceptions) available we don't remove all child nodes of the `#full_list` element.
Also, delete the `fixOutsideWorldLinks` function, is no longer required.
=> Empty #full_list if there are no nodes available

lib/ex_doc/formatter/html.ex
Some tests:
```
$ aux="../ex_doc/bin/ex_doc ExUnit 1.0.5 lib/ex_unit/ebin -u https://github.com/elixir-lang/elixir -o doc/ex_unit -p http://elixir-lang.org/docs.html"
$ # current version
$ eval "time $aux"
../ex_doc/bin/ex_doc ExUnit 1.0.5 lib/ex_unit/ebin -u  -o doc/ex_unit -p   0.67s user 0.27s system 125% cpu 0.751 total
$ # new version, sync mode (-m given)
$ eval "time $aux -m ExUnit"
../ex_doc/bin/ex_doc ExUnit 1.0.5 lib/ex_unit/ebin -u  -o doc/ex_unit -p  -m   0.67s user 0.25s system 135% cpu 0.673 total
$ # new version, async mode (without entry-point module in docs)
$ eval "time $aux"
./ex_doc/bin/ex_doc ExUnit 1.0.5 lib/ex_unit/ebin -u  -o doc/ex_unit -p   0.52s user 0.23s system 123% cpu 0.604 total
```
=> WIP: Improve build performance

lib/ex_doc/formatter/html/templates/js/app.js, lib/ex_doc/formatter/html/templates/sidebar_template.eex
The `input` event fires whenever the user has modified the data of
the control. So, this already covers the `keyup`, `paste`, etc.
This commit also includes the following:
* Add documentation to some JS functions
* Fix links in navigation area
* Change the `evnt`, `evt` variables to `e` for consistency
* Change `bind` to `on` method (jQuery)
Fix #222
=> Avoid double click in a sidebar link after search

lib/ex_doc/formatter/html/templates/js/app.js
This commit fix the following issue mentioned in #231 and #232 
> Switching between "Modules, Exceptions and Protocols" once you searched
> something, it will will never shot the results in the other sections,
> and something the loading icon hangs there endlessly.
/cc @eksperimental @ericmj @josevalim
=> Fix the switch between nav elements

lib/ex_doc/formatter/html/templates/sidebar_template.eex
This commit fix the following issue mentioned on elixir #235:
> The `input` element (used as a search field) could be improve if we use
> the `<label>` element tag to describe the functionality of the search
> field, is not enough the placeholder attribute inside of the `<input>`
> element tag.
=> Add label tag element for search input field

lib/ex_doc/formatter/html/templates/js/app.js
The navigation area only accepts `exceptions` and `protocols` as module types, this means that we need to ignore others (e.g. behaviour). #232
=> Limit the module types in the navigation area

lib/ex_doc/formatter/html/autolink.ex, lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/formatter/html/templates/overview_template.eex, lib/ex_doc/formatter/html/templates/readme_template.eex, test/ex_doc/formatter/html/autolink_test.exs, test/ex_doc/formatter/html/templates_test.exs
Each local link that points to the current page must link to the top of the page instead, this way we can avoid reload the page each time that somebody follow those links. Fix #200
=> Update local links to the current page

lib/ex_doc/formatter/html/templates/css/style.css, lib/ex_doc/formatter/html/templates/overview_entry_template.eex, lib/ex_doc/formatter/html/templates/summary_template.eex
fixes the bacground issue when no description is provided.
http://elixir-lang.org/docs/master/elixir/overview.html#exceptions_summary
Display empty cells, so tables look consistent.
Make use of the css property "empty-cells"
https://developer.mozilla.org/en/docs/Web/CSS/empty-cells
=> deal with empty table cells

LICENSE, README.md, lib/ex_doc/formatter/html/templates/css/elixir.css
* normalized.css added to LICENSE
* Links to the respective projects added
* Removed  "CSS Template: lib/ex_doc/formatter/html/templates/css/style.css",
since not only that the default template itself (css, html and js) is
based on YARD
* Tab replace with 2 spaces in the YARD license
* Link to license added in /lib/ex_doc/formatter/html/templates/css/elixir.css
=> Licenses updated

bin/ex_doc
`Mix.env` is hardcoded in bin/ex_doc
```sh
$ reset; MIX_ENV=test mix do clean, compile, test
$ bin/elixir ../ex_doc/bin/ex_doc "EEx" "1.1.0-dev" "lib/eex/ebin" -m "EEx" -u "https://github.com/elixir-lang/elixir" --source-ref "22ab2d9cf8db6f6a2a7f7406c53500cdf870ee7b" -o doc/eex -p http://elixir-lang.org/docs.html
Error: cannot generate docs because ExDoc.CLI module is not available. Please run `mix compile` before or ensure ExDoc is available.
** (exit) 1
/home/eksperimental/ex_doc/bin/ex_doc:10: (file)
(elixir) lib/code.ex:363: Code.require_file/2
$ MIX_ENV=test bin/elixir ../ex_doc/bin/ex_doc "EEx" "1.1.0-dev" "lib/eex/ebin" -m "EEx" -u "https://github.com/elixir-lang/elixir" --source-ref "22ab2d9cf8db6f6a2a7f7406c53500cdf870ee7b" -o doc/eex -p http://elixir-lang.org/docs.html
Error: …
```
=> fix PATH in bin/ex_doc (hardcoded Mix.env)

lib/ex_doc.ex, lib/ex_doc/cli.ex, lib/ex_doc/formatter/html.ex, lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/formatter/html/templates/overview_template.eex, lib/ex_doc/formatter/html/templates/readme_template.eex, lib/ex_doc/formatter/html/templates/redirect_template.eex, lib/ex_doc/formatter/html/templates/sidebar_template.eex, lib/mix/tasks/docs.ex, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/formatter/html_test.exs, test/ex_doc_test.exs
The current implementation of the index page made of a copy of
the "main" page in index.html. Creating an unncessary duplicate page.
This commit creates an HTML redirect page.
=> Redirect template added & Duplicate index page removed

lib/ex_doc/formatter/html/templates/redirect_template.eex
Fixes: https://github.com/elixir-lang/ex_doc/issues/279 (introduced by https://github.com/elixir-lang/ex_doc/pull/265)
* Removes text from telling user is being redirected
* Javascript redirection removed
* Show only project name in `<title>`
* Move `<meta charsert>` to the very top
* Add: `<meta name="index" content="noindex" />` so it's not indexed by search engines
Browser History shows now the Title of the project.
You can go back and forth, without seeing the redirect page in the middle.
=> Cleaner redirect template

lib/ex_doc/cli.ex, lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/formatter/html/templates/head_template.eex, lib/ex_doc/formatter/html/templates/module_template.eex, lib/ex_doc/formatter/html/templates/overview_template.eex, lib/ex_doc/formatter/html/templates/readme_template.eex, lib/ex_doc/formatter/html/templates/redirect_template.eex, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/formatter/html_test.exs
* align text in the ExDoc.CLI help
* ~~close void elements in head_template~~
* Add Project Name and Version to `<title>`
- This information should be present to avoid confusion with different versions. Specially when bookmarking.
* Get rid of `~r/ /` in favour of `~r{ }`
To avoid escaping slashes
* head_template standardized & titles improved
* head_template : Now it takes 2 args. Stadardize with the rest of the templates,
taking "config" as first argument
* ~~head_template: titles improved, to not so duplicate information when a module
has the same name as the project. ex: ExUnit,
instead of reading: "ExUnit – ExUnit v1.1.0-dev", it now reads:
"ExUnit v1.1.0-dev – Documentation"~~
=> Several Small fixes

.gitattributes
Just treat them as binaries,
so it won't display the diff when we do `git log -p`
and run a diff.
Otherwise it spoils the output with such big files.
/cc @Dignifiedquire @milmazz
=> Do no show diff in /lib/ex_doc/formatter/html/templates/dist/*

lib/ex_doc.ex, lib/ex_doc/formatter/html.ex, test/ex_doc/formatter/html_test.exs, test/ex_doc_test.exs
[I have accidentally closed: https://github.com/elixir-lang/ex_doc/pull/301]
...and not directly.
This way we can assure the configs are passed through ExDoc, doing
the preconfiguration and the normalization.
=> Enforce call to ExDoc.Formatter.HTML.run/3 to be done from ExDoc,

.travis.yml, assets/test/helpers.spec.js
This PR includes certain improvements when we use Travis:
- Use the new container-based infrastructure
- Cache directories `node_modules` (for `npm install`) and `deps` (for `mix deps.get`)
- Use the latest release of Pandoc
- Fix a little ESLint error, with this the build result exit with 0 (OK)
@josevalim Let me know what do you think about this? Is it OK to cache `deps` directory?
=> [TravisCI] Migrate from legacy to container-based infrastructure

lib/ex_doc/retriever.ex
Follow-up on #371.
Docs building is successful.
=> Fallback to doc line if there is no fun definition in abstract code

.travis.yml
This PR includes the Mix task `coveralls.travis`, which allows to submit the *coverage* results to the [coveralls.io](https://coveralls.io) servers when TravisCI build is executed.
Then we can show a *badge* in our README that shows the results.
@josevalim I think that to allow this, first [coveralls.io](https://coveralls.io) needs your authorization.
The coverage history is similar to this page:
https://coveralls.io/github/parroty/excoveralls
=> Post coverage to travis

lib/ex_doc/formatter/html.ex, test/ex_doc/formatter/html_test.exs
This change will allow reuse the `generate_assets` function from others formatters (e.g. EPUB)
=> Update generate_assets to be a public function

lib/ex_doc/cli.ex, test/ex_doc/cli_test.exs
We now support:
```sh
$ bin/ex_doc --version
ExDoc v0.10.0-dev
$ bin/ex_doc --version number
0.10.0-dev
$ bin/ex_doc --version oops
** (RuntimeError) unknown value "oops" for --version
lib/ex_doc/cli.ex:22: ExDoc.CLI.do_version/1
(elixir) lib/code.ex:363: Code.require_file/2
```
closes #399
=> ExDoc.CLI: support --version option

lib/ex_doc/formatter/html/autolink.ex, lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/formatter/html/templates/api_reference_entry_template.eex, lib/ex_doc/formatter/html/templates/detail_template.eex, lib/ex_doc/formatter/html/templates/redirect_template.eex, lib/ex_doc/formatter/html/templates/sidebar_template.eex, lib/ex_doc/formatter/html/templates/summary_item_template.eex, lib/ex_doc/formatter/html/templates/type_detail_template.eex, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/formatter/html_test.exs
This commits fixes every single bug,
thus it makes the docs generated (checked only on the Elixir docs)
valid HTML5 documents.
I throughly tested everything,
we didn't have that many issues. but they were hard to fix,
I have sent a few a few PRs to earmark because some issues came from there.
there is on last PR that needs to be reviewed and merged.
I have validated the Elixir docs using html-proofer and html5validator,
no internal broken links found, only one issue and we are 100% valid.
I will may need help to fix it.
OK. trying to push this so we can test the longer the better..
=> Makes ExDoc generate Valid HTML5 pages

assets/js/events.js
I was seeing the [Ecto.Changeset doc](http://hexdocs.pm/ecto/Ecto.Changeset.html) and the anchors on sidebar doesn't works in Firefox. 
The problems is the global ```event``` is undefined in Firefox. I changed to use event from handler argument
Error: ```ReferenceError: event is not defined```
Firefox: 40.0.3 
OS: UbuntuGNOME linux
=> fix handleAnchor

lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/formatter/html/templates/summary_template.eex
enc() helper added.
Checked by htmlproof and html5validator
Also removed the Enum.sort() that messed up the order in summary
=> Validate anchor links in sidebar + fix summary sorting

lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/retriever.ex, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/formatter/html_test.exs
this commit improves the removal of trailing punctuation from summary
semicolon has been added as it appeared showing up in a quiet a few
cases in summaries
tests added
ExDoc.Formatter.HTML.Templates.api_reference_page/5 added to ease testing.
and also added specs for  ExDoc.Retriever.docs_from_*
=> remove trailing semicolon from  Synopsis

README.md
Getting help for ex_doc wasn't obvious.   First you have to find the `mix help docs` reference which was in a non-obvious place, and then you had to figure out why it didn't work (because deps hadn't been compiled yet).    
I moved the line describing this under using with mix and added guidance about building deps.
=> improved instrucitons for getting help

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs
The function names need to be URL escaped in the auto-generated links as well. Other spots I found like the links in the sidebar were already corrected.
For example [this section in the elixir docs](http://elixir-lang.org/docs/stable/elixir/Kernel.SpecialForms.html#::/2) links to `<<>>/1`, which generates the following markup:
```html
<a href="#&lt;&lt;&gt;&gt;/1">...</a>
```
However, it should be like this
```html
<a href="#%3C%3C%3E%3E/1">...</a>
```
Note that I also changed the specs, which now assert that surrounding spaces are removed. This is now in line with the way `Autolink.project_functions` works, which also strips spaces.
=> Fix autolink anchors for non URL safe function names

lib/ex_doc/cli.ex, lib/ex_doc/formatter/html.ex, lib/ex_doc/formatter/html/templates/not_found_template.eex, lib/mix/tasks/docs.ex, test/ex_doc/formatter/html_test.exs
This PR removes the `extra-` prefix from the additional documentation (specified with the option `extras`), this was suggested by @wsmoak, you can see more details about the discussion [in the mailing list](https://groups.google.com/d/msg/elixir-lang-core/UzhyIhvQsC8/S_W5sk3yDAAJ) and #462
=> Get rid of the 'extras-' prefix

lib/ex_doc/formatter/html.ex, lib/mix/tasks/docs.ex, test/ex_doc/formatter/html_test.exs
Assuming the following configuration:
```elixir
docs: [source_ref: "v#{@version}", main: "Phoenix", logo: "logo.png",
extras: ["README.md",
"CHANGELOG.md": [title: "Changes"],
"CODE_OF_CONDUCT.md": [path: "code-of-conduct"],
"CONTRIBUTING.md": [path: "contributors", title: "We need your help!"]]],
```
Now the results are:
Input File | Output File | Menu name
------------ | --------------- | ---------------
`README.md` | `readme.html` | `README`
`CHANGELOG.md` | `changelog.html` | `Changes`
`CODE_OF_CONDUCT.md` | `code-of-conduct.html` | `CODE_OF_CONDUCT`
`CONTRIBUTING.md` | `contributors.html` | `We need your help!"
Related issues: #469 #468 #450
=> Allow definition of the path/title for extra files

lib/ex_doc/formatter/html.ex, test/ex_doc/formatter/html_test.exs, test/fixtures/ExtraPage.md
Take the first line beginning with `# ` (the first `<h1>`) as the menu title, if a title wasn't specified in the configuration.
ExDoc already uses the `<h2>`'s as sub-menu items, so this seems natural to do.
Without this, I have to duplicate the header text in both the markdown file and the configuration.
Advice on implementation and testing is appreciated!  @bbense suggested using multiple defined functions instead of the conditional, see [1], but this seems to fit better with the other code in the module.
[1] http://wiki.wsmoak.net/cgi-bin/wiki.pl?ElixirSlack20151110
=> Use first <h1> as menu title if title is not configured

lib/ex_doc.ex
fix a typo in ex_doc module docstring
=> fix typo in ex_doc module

lib/ex_doc/retriever.ex, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/retriever_test.exs, test/fixtures/behaviour.ex
When a callback is defined, an attempt is made to derive the argument
type from the name. If the typespec has more than one type option then
the argument name is given as "|"
An explicit check for this format is now in place, and the "arg#{i}"
case is used.
=> fix(ExDoc.Retriever): fix invalid arguments for callbacks

lib/ex_doc/retriever.ex
@josevalim You merged my last pull request just as I was amending this. Sorry.
=> chore(ExDoc.Retriever): pattern match :| for types

lib/ex_doc/formatter/html/autolink.ex, test/fixtures/behaviour.ex
* Avoid warnings on variables defined inside a conditional (Elixir v1.0.2-dev)
* Avoid `string()` type, for strings, use `String.t()` instead.
=> Unsafe variables and string() type

assets/js/sidebar.js, assets/less/sidebar.less
Solves #492 
This solution uses media queries and an extra JS function to cater to different screen widths.
While working on this feature, I encountered several different ways this could be done.
I started by just adding a couple CSS media queries on the sidebar, which works great until you show/hide the sidebar. Because the width of the sidebar is statically set in the JS file that animates it, as soon as you toggle the sidebar, the new CSS gets overridden.
The solution I went with for this PR is to add CSS media queries, and change the width variable in JS to change based on screen width. After the sidebar is opened, the inline styles that get added are removed so the CSS takes over again. This probably isn't the absolute *best* solution, but it works and it's simple.
Here are some …
=> Take advantage of extra space on large screens by widening sidebar

lib/ex_doc/formatter/html.ex, lib/ex_doc/formatter/html/autolink.ex
We are using ex_doc (v0.11.1) to generate docs for several projects with our CI server. Unfortunately our CI server's CPU resource is fairly poor and uses NFS volume. Recently we find that our `mix docs` job is failing due to timeout of `Task.await`. Some of our modules contain macro-generated many `def`s.
Stacktrace:
```
** (exit) exited in: Task.await(%Task{pid: #PID<0.1480.0>, ref: #Reference<0.0.1.26455>}, 5000)
** (EXIT) time out
(elixir) lib/task.ex:274: Task.await/2
(elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
(elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
(elixir) lib/enum.ex:1043: Enum.map/2
lib/ex_doc/formatter/html.ex:23: ExDoc.Formatter.HTML.run/2
lib/mix/tasks/docs.ex:96: Mix.Tasks.Docs.run/3
(mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
```
In this …
=> Don't abort by timeout of Task.await

lib/ex_doc/retriever.ex, test/ex_doc/retriever_test.exs, test/ex_doc/retriever_test/Elixir.ExDoc.RetrieverTest.ModuleNotCompiledWithFlagDocs.erl
Hello,
I'm using ex_doc 0.10.0 with Elixir 1.1.1 and Erlang 18.1 under 64-bit Linux. :smiley:
[Following this guide](http://andrealeopardi.com/posts/tokenizing-and-parsing-in-elixir-using-leex-and-yecc/), I created a `src/Elixir.My.List.Lexer.xrl` file containing:
```erlang
Definitions.
INT        = [0-9]+
ATOM       = :[a-z_]+
WHITESPACE = [\s\t\n\r]
Rules.
{INT}         : {token, {int,  TokenLine, list_to_integer(TokenChars)}}.
{ATOM}        : {token, {atom, TokenLine, to_atom(TokenChars)}}.
\[            : {token, {'[',  TokenLine}}.
\]            : {token, {']',  TokenLine}}.
,             : {token, {',',  TokenLine}}.
{WHITESPACE}+ : skip_token.
Erlang code.
to_atom([$:|Chars]) ->
list_to_atom(Chars).
```
Afterwards, I get the following error when running `mix docs`: :scream:
```sh
$ …
```
=> ** (ExDoc.Retriever.Error) module MyListLexer was not compiled with flag --docs

lib/ex_doc/retriever.ex
I try to generate docs for ecto master, but it failed. I found it's related to `@macrocallback`, so I fixed it. I didn't test this because ex_doc needs to support Elixir 1.0 for the moment, but this should work.
=> support doc of @macrocallback

README.md, lib/ex_doc/markdown.ex
This addresses a few things I neglected in #501:
* Add cmark to the docs in `lib/ex_doc/markdown.ex` and update the `@markdown_processors` mod attribute so Cmark can be appropriately found along with the other processors.
* Add cmark mention to the README.
Some subjective changes in the second commit:
* Expand the instructions around using different markdown processors.
* Add shell syntax highlighting to relevant examples in README
* Juggle some link definitions in the README.
If you like I can pop off the second commit and re-push for the sake of limiting the changes.
=> Update docs for cmark

README.md
Otherwise people will have a hard time to use cmark as a parser. :smile_cat:
=> Fix cmark.ex dependency line

lib/ex_doc/formatter/html.ex, test/ex_doc/formatter/html_test.exs
Often, the markdown documents to be included in the generated docs are meant to be viewable on GitHub, especially README.md used as the default page on GitHub.
When attempting to do intra-document linking e.g. `[Examples][#examples]` to link to the Examples header in the same document, it works on GitHub rendered page, but fails on the generated HTML docs, due to the different capitalization of the required URL fragment/id attribute.
ex_docs preserves the capitalization of the header text when generating the `id` attribute while GitHub downcases them, making it incompatible with each other. 
Since it's unlikely we can get GitHub to change, given it will break all existing public #fragment links, the choice is for ex_doc to adopt GitHub's format for universal compatibility.
Here's the pull …
=> Downcase generated id from header to be consistent with GitHub format.

assets/less/content.less
I've added `font-feature-settings` for Firefox and `-webkit-font-variant-ligatures` for Safari to fix the problem of "invisible Fs" when `f` and `i` appear together in the docs. Fixes #511.
=> Fix ligature issue on Firefox and Safari

lib/ex_doc/formatter/html.ex
Looks like a result of fixing the 1.3.0 warnings commit.
=> Fixed crash when no logo

lib/ex_doc.ex, lib/ex_doc/cli.ex, lib/ex_doc/formatter/html.ex, lib/ex_doc/formatter/html/templates/head_template.eex, lib/mix/tasks/docs.ex, test/ex_doc/formatter/html_test.exs
Indicate the preferred URL with `rel="canonical"` link element, this is useful to avoid multiple versions in search results. Fixes #499
=> Use canonical URLs

assets/js/events.js
This fixes an issue (#523) where hitting the space bar after loading a module's documentation doesn't work.
I set the tabindex through JS rather than changing the template because I felt like it would be clearer to a reader since the whole thing is in one place.
=> focus on content element on document ready

lib/ex_doc/formatter/html/autolink.ex
Note that the regexp is updated in a way that theoretically allows digits at the front of a function name. In practice this will of course not happen because Elixir itself will reject variable/function names that start with numbers (which the regexp results are filtered against on line 209 in autolink.ex).
I've done it this way because I think the regexp will stay more readable like this. The same is also true for underscores and `?` and `!` by the way, that already were this way.
:smiley:
=> Fixes #528, autolink regexp now allows digits in function names.

lib/ex_doc/retriever.ex, test/ex_doc/retriever_test.exs
It is normally masked by `Path.relative_to` processing, but if
`source_root` set to `nil` in the configuration, `ex_doc`
fails (`lib/ex_doc/retriever.ex:410:` `** (FunctionClauseError) no
function clause matching in Regex.replace/4`)
=> Fix `source_path` return of char list

mix.exs
On latest elixir master:
```
==> ex_doc
Compiling 12 files (.ex)
warning: function Cmark.to_html/1 is undefined (module Cmark is not available)
lib/ex_doc/markdown/cmark.ex:18
warning: function Markdown.to_html/2 is undefined (module Markdown is not available)
lib/ex_doc/markdown/hoedown.ex:29
Generated ex_doc app
```
=> Add xref exclude to `mix.exs` for `Cmark` and `Markdown`.

assets/less/content/general.less
The nested list are written like this:
```
- Installation
- Why?
- Description
- QueryConfig
- Serializer
- DataTransform
- AttributeTransform
- Examples
```
Problem is, for each "root" element which has a nested list, a `p` element is inserted. This makes the rendered list looks a bit weird. Note that the GitHub markdown renderer doesn’t insert extra `p` element on nested list.
**Before**:
**After**:
=> Update general.less to better support nested list

lib/ex_doc/formatter/html/templates/detail_template.eex, lib/ex_doc/formatter/html/templates/summary_item_template.eex, lib/ex_doc/retriever.ex
This PR is supposed to add support for `@optional_callbacks`, that will be introduced in 1.3.0 (and close #541). I'm not sure what the process of rolling this out would look like: do we wait for when 1.3 will be released? I think this changes are harmless when `@optional_callbacks` is not supported.
Also, I really don't like this solution's implementation because:
1. we get to reimplement something very very similar to `Kernel.Typespec.beam_callbacks/1`: should we introduce `Kernel.Typespec.beam_optional_callbacks/1` in Elixir itself?
2. this solution displays optional callbacks in a separate section ("Optional callbacks") than regular callbacks, but ideally I think we should just mark callbacks as optional (e.g., with `(optional)` near the signature); sadly, I lack the design skills for …
=> Add support for optional behaviour callbacks

lib/ex_doc/formatter/html/templates/head_template.eex
When loading the page in night mode there is a small delay that causes the page to flash white while the javascript loads.  This is obviously more problematic the longer page is and as such affects documentation more than most.
=> Fix flash of unstyled content

lib/ex_doc/markdown/pandoc.ex
Changing deprecated crypto:rand_bytes/1 for crypto:strong_rand_bytes/1
=> Removing "crypto:rand_bytes/1" compiler warning

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs
This is a pull request for #588. The missing piece was the optional callback header `c:` was missing in the regular expression digesting the code pieces.
=> Local Callbacks (#588)

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs
Evaluating the `t:` prefix to a type with function syntax. The implementation took a little detour, because it took a while to realize that links to types without arity shall not work. Essentially, this make the code easier. 
I added also a better matching Module regex, since numbers and underscores are valid characters in module names.
=> Autolinking to types

assets/less/content/code.less
This change allow mobile devices in portrait to scroll snippets horizontally
=> Allow horizontal scroll for code snippets on mobile devices

lib/ex_doc/formatter/html.ex, lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/formatter/html/templates/extra_template.eex, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/retriever_test.exs, test/fixtures/compiled_with_docs.ex
Ensure that moduledocs and extra pages use the markdown HTML entity escaping.
Remove HTML entities from header IDs.
Fixes #587
=> Stop escaping linked h2s

lib/ex_doc/formatter/epub/templates/toc_template.eex
Use double quotes like the rest of the document, and uppercase UTF-8 like:
https://github.com/elixir-lang/ex_doc/blob/adfbbd1ef29d7bdba77bceef9a350a9f2eefc0bb/lib/ex_doc/formatter/epub/templates/content_template.eex
=> Update XML header to be consistent

lib/ex_doc.ex, lib/ex_doc/formatter/epub.ex, lib/ex_doc/formatter/html.ex, lib/ex_doc/retriever.ex
The idea behind this PR is to use `ExDoc.Config.t` instead of `%ExDoc.Config{}` when we're referring to that struct. The same behavior for `ExDoc.{Module,Function,Type}Node.t`. wdyt?
=> Define new types

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/epub/templates_test.exs, test/ex_doc/formatter/html/autolink_test.exs, test/ex_doc/formatter/html/templates_test.exs
Fixes #607
Before:
After:
Not sure if the change to types (dropping highlight on type name on left) is desired, but a) the link jumps to the same exact place, b) it seems more consistent as this is how functions are highlighted and c) implementation-wise it was easier to do. It's def. possible to scope this change to just functions though.
Btw, here're the changes this PR would have made on Elixir 1.3.4 docs: https://gist.github.com/wojtekmach/601771cbedac5a47d63c1c47d21d47e5
=> Do not highlight function or type name left of ::

lib/ex_doc/formatter/html/templates.ex
Noticed that opaque types aren't correctly auto-linked. See e.g.: `t` here: http://elixir-lang.org/docs/master/elixir/MapSet.html#delete/2
=> Fix autolinking to opaque type

lib/ex_doc/retriever.ex, test/ex_doc/retriever_test.exs, test/fixtures/behaviour.ex
As discussed over on IRC. A function that is not explicitly annotated with `@doc false` and doesn't have docs, but the callback does - will include callback docs.
=> In case function has no docs, use the ones from callback

lib/ex_doc.ex, lib/ex_doc/cli.ex, test/ex_doc/formatter/html_test.exs
GitLab has become quite popular, and its source URL scheme is identical
to GitHub's. That makes it useful and easy to support by default.
=> Automatically detect GitLab source URL patterns

lib/ex_doc/formatter/epub/templates.ex, lib/ex_doc/formatter/epub/templates/module_template.eex, lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/formatter/html/templates/module_template.eex, lib/ex_doc/retriever.ex, test/ex_doc/formatter/epub/templates_test.exs, test/ex_doc/formatter/html/templates_test.exs
Per #646, this removes the top-level distinction between functions and
macros in the sidebar. Macros are listed alongside functions and include
an additional "(macro)" annotation tag:
=> List both functions and macros under "Functions"

lib/ex_doc/formatter/html.ex, test/ex_doc/formatter/html_test.exs
This makes it a little more obvious when `main:` references an invalid
document or node.
=> Warn when redirecting to a non-existent file

lib/ex_doc/retriever.ex, test/ex_doc/retriever_test.exs, test/fixtures/compiled_with_docs.ex
First shot at #667.
With this commit, we 
* annotate `__struct__/0` functions (like we do with macros and optional callbacks)
* display them as `%Task{}` instead of `__struct__/0` (for the `Task` example of course)
I am still showing them as `__struct__/0` in their anchor and in the sidebar, I am not sure how to proceed: for example, the anchor is URL-encoded as hell if we show `%Task{}`. Thoughts?
=> Handle __struct__/0 by displaying the struct instead

lib/ex_doc/markdown/earmark.ex, mix.exs
Earmark.to_html was [deprecated as of v1.1](https://github.com/pragdave/earmark/commit/8f8a05f18fcf596b20a97d73a74dcc3745fc802a). This changes to use the new `as_html!` which prints any errors to STDERR automatically.
I noticed the other day when [updating dependencies](https://github.com/mmmries/sqlitex/pull/51) that generating docs would generate a bunch of dependency warnings like this:
```
$ mix docs
warning: usage of `Earmark.to_html` is deprecated.
Use `Earmark.as_html!` instead, or use `Earmark.as_html` which returns a tuple `{html, errors}`
warning: usage of `Earmark.to_html` is deprecated.
Use `Earmark.as_html!` instead, or use `Earmark.as_html` which returns a tuple `{html, errors}`
warning: usage of `Earmark.to_html` is deprecated.
...
```
Seemed like a pretty simple fix to use …
=> use Earmark.as_html!

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs, test/ex_doc/formatter/html/templates_test.exs
=> 657 properly set link in types with parameter

assets/less/sidebar.less
Changes project name wrapping to use normal word wrapping
instead of break-all. This prevents a long project name from
being wrapped mid-word while still allowing long words to
be wrapped properly.
Fixes #696
=> Fix project name wrapping

test/ex_doc/formatter/html_test.exs
Closes https://github.com/elixir-lang/ex_doc/issues/688
=> Fix warning in ExDoc.Formatter.HTMLTest

lib/ex_doc/formatter/html/templates.ex, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/formatter/html_test.exs, test/fixtures/README.md
I cannot run tests locally as it seems cmark depends on `make` tool and i have no means to build it on windows :(
=> Strip nesting html tags in headers. Closes #705

lib/ex_doc/formatter/html/templates.ex, test/ex_doc/formatter/html/templates_test.exs
Fix for the malformed h2 links. Also added some tests for the link headings and sidebar items. Additional test cases might be desired?
=> Fix malformed h2 links

assets/js/search.js, assets/js/templates/search-results.handlebars
I'm not sure this is the correct way but in the HTML It Works™. Tests do not pass but I suspect that's related to #723? Any pointers are appreciated :).
=> Add types to the search results

assets/less/variables.less
The font stack has been chosen carefully to be supported (99%+) on Windows, Mac and Linux assuming Merriweather fails to load.
To some extent (as much as I think is reasonable) closes: #695
=> Change font stack, based on availability on different platforms

test/ex_doc/formatter/html/templates_test.exs
ExDoc already depends on Elixir ~> 1.3 where `String.trim_trailing/1` was introduced, so there's no backwards compatibility issue.
=> Use String.trim_trailing/1 over the deprecated String.rstrip/1

lib/ex_doc/retriever.ex
Closes #690. Not sure I should add a test for this since the whole thing of getting the signature from the typespec is only tested "on the side" (for example [here](https://github.com/elixir-lang/ex_doc/blob/527e0602598f7e283fa15d8aad9876b63334f9dd/test/ex_doc/retriever_test.exs#L181)) and it would mean fiddling with the fixtures behaviours.
=> Fix callback signature when arguments are typed as functions

lib/ex_doc.ex, test/ex_doc/formatter/html_test.exs
Closes https://github.com/elixir-lang/ex_doc/issues/717
It rewrites "http" to "https" when building source_url_pattern.
=> Deal with http:// when guessing source_url_pattern

lib/mix/tasks/docs.ex, test/mix/tasks/docs_test.exs
It will raise with ArgumentError if :version key is not provided in config.
/cc @ericmj
=> Raise if version is not provided in Docs task config

lib/ex_doc/formatter/html/templates.ex, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/formatter/html_test.exs, test/ex_doc/retriever_test.exs, test/fixtures/compiled_with_docs.ex
Currently, only `<h2>` headings are linked in generated documentation. This PR links `<h3>`s as well. For example:
- In a page: `/doc/elixir/operators.html#term-ordering`
- In a `@moduledoc` heading: `/doc/mix/Mix.Tasks.Xref.html#module-warnings`
- In a detail heading (i.e., `@doc` for a function): `/doc/elixir/Time.html#compare/2-examples`
Addresses https://github.com/elixir-lang/ex_doc/issues/701.
=> Link `<h3>` headings

lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/formatter/html/templates/detail_template.eex
When merged, this will fix #509
Firefox (and probably other browsers) expect the URI of an anchor to be urlencoded
but the actual target to be NOT encoded. Due to this behaviour, links to functions
with special characters won't work.
While RFC3986 is very clear on how URIs have to be formatted, there is no clear
specification on how link targets actually should (or shouldn't) be encoded.
There are lose guidelines for HTML4/HTML5 but they rarely cover special characters.
Since most browsers seem to have adapted to also match encoded anchor targets,
this commit does not change but only extend the current behaviour by adding a
second, unencoded target to the template, similar to what is already done when
linking to a function with optional parameters, which results in target links
with …
=> Add unencoded link target for functions with special chars

lib/ex_doc/retriever.ex, test/ex_doc/retriever_test.exs
=> fix: remove extra term() argument at start of macro spec

lib/ex_doc/markdown.ex, lib/ex_doc/markdown/cmark.ex, lib/ex_doc/markdown/earmark.ex
Code blocks are now handled by the markdown modules,
and ExDoc doesn't do any post-processing.
The modules bundled with ExDoc were updated to reflect this.
The goal of this change is to make it easier to use alternative Markdown
implementations.
This might break compatibility for people that are already usin Markdown
extensions.
The code for the Hoedown module wasn't changed because it already handled the postprocessing of code blocks itself.
All unit tests pass, and my visual integration test with Earmark on a real project showed no differences.
=> Markdown modules are now 100% responsible for code

lib/ex_doc.ex, lib/ex_doc/formatter/epub/templates/extra_template.eex, lib/ex_doc/formatter/epub/templates/head_template.eex, lib/ex_doc/formatter/epub/templates/module_template.eex, lib/ex_doc/formatter/epub/templates/nav_template.eex, lib/ex_doc/formatter/epub/templates/title_template.eex, lib/ex_doc/formatter/html/templates/footer_template.eex, lib/ex_doc/formatter/html/templates/head_template.eex, lib/mix/tasks/docs.ex, test/ex_doc/formatter/epub_test.exs, test/ex_doc/formatter/html_test.exs
All tests pass (which means the extra content is actually being included), and he output is good on visual inspection on my reader. If this is merged, we should make a release so that it can be used for hex packages.
=> before_closing_*_tag works on EPUB too

lib/ex_doc/formatter/epub.ex, test/ex_doc/formatter/epub_test.exs
Previously, the epub formatter defaulted to a filename in the following format:
> Phoenix-v1.3.0.epub
This commit changes it to:
> Phoenix.epub
When published to hexdocs, the version will already be specified in the url.
This means if the epub file is linked to in the docs, it will not be updated
each time there is a new version.
=> Remove version name from epub formatter

.travis.yml
On Aug 31st 2017 Travis CI updated their default Linux version to 14.04
https://blog.travis-ci.com/2017-08-31-trusty-as-default-status
As a result, Firefox was updated to Firefox 55, which has headless
support, however, this version of Firefox does not appear to be working
with Travis CI. There is an issue being tracked at:
https://github.com/travis-ci/travis-ci/issues/8242
For now, the easiest fix is to lock the Firefox version.
=> Lock Firefox version to 54.0 for Travis CI tests

assets/less/layout.less
When the page content does not fill the full height the sidebar closing/opening animation looks odd.  
**Before:**  
**After:**
=> Fix .main height to 100%

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs, test/test_helper.exs
=> Run code formatter on typespecs

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs, test/ex_doc/formatter/html/templates_test.exs
Ref #682 - however here we only handle typespecs in this PR
Ref [elixir-lang-core: Anchor built-in types](https://groups.google.com/d/msg/elixir-lang-core/HgOkmWK--OY/Eb2rrvQ1BQAJ) - however we just link to a section of that page and not to particular item
Example:
Before:
After:
Note: Pretty sure the different indentation is because the "After" version has more `_pX_` placeholders and so it's shorter when formatting.
=> Autolink basic and built-in types in typespecs

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs, test/ex_doc/formatter/html/templates_test.exs, test/fixtures/types_and_specs.ex
=> Autolink basic/built-in types and special forms in docs

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs
=> Autolink Kernel functions

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs
=> Allow custom links in Autolink.elixir_functions

lib/mix/tasks/docs.ex
Spotted a reallyyy small typo error while reading `mix help docs`.
=> Fix Mix.Tasks.Docs moduledoc typo

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs
Fixes #831
Also general improvements (see added tests)
=> Fix formatting typespecs

lib/ex_doc/markdown/earmark.ex
Wanted to add a [task list](https://help.github.com/articles/about-task-lists/) to the docs in a personal project, but found that Earmark does not support them. I want to write a custom plugin to do it, though it doesn't seem to be possible to enable the plugin through ex_doc. This PR should fix that.
=> Add plugins support to Earmark processor

lib/ex_doc/formatter/html/templates/footer_template.eex
`[rel="noopener"]` is added to external links having `[target="_blank"]`  to deny access to `window.opener`. [Here](https://developers.google.com/web/tools/lighthouse/audits/noopener) is a quick rundown on why it is important.
=> Use [rel="noopener"] on external links

lib/ex_doc/retriever.ex
Additionally sort special forms alphabetically.
=> Do not append () in __STACKTRACE__ signature

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs
This PR adds a negative lookbehind for multiline codeblocks, to fix an issue where a module name in an inline codeblock after a multiline codeblock didn't get correctly matched, due to the regex matching from the multiline codeblock to the inline codeblock.
Before: https://regex101.com/r/Du8vUp/1
After: https://regex101.com/r/Zit4pj/1
=> Fix Elixir module matcher RegEx

lib/ex_doc/retriever.ex, test/fixtures/types_and_specs.ex
This PR fixes the bug when ExDoc included documentation for types with `@typedoc false`.
Closes #857
=> Exclude types with `@typedoc false` from generated documentation

lib/ex_doc/retriever.ex
The idea behind this PR is avoid this kind of warnings under Elixir 1.7.0-dev:
```console
λ mix test
Compiling 3 files (.ex)
Excluding tags: [no_formatter: true]
..warning: Kernel.Typespec.beam_specs/1 is deprecated, please use Code.Typespec.fetch_specs/1 instead
(elixir) lib/kernel/typespec.ex:48: Kernel.Typespec.beam_specs/1
(ex_doc) lib/ex_doc/retriever.ex:481: ExDoc.Retriever.get_specs/1
(ex_doc) lib/ex_doc/retriever.ex:195: ExDoc.Retriever.get_module_info/2
(ex_doc) lib/ex_doc/retriever.ex:166: ExDoc.Retriever.generate_node/3
(elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
(ex_doc) lib/ex_doc/retriever.ex:116: ExDoc.Retriever.docs_from_modules/2
test/ex_doc/formatter/epub/templates_test.exs:30: ExDoc.Formatter.EPUB.TemplatesTest.get_module_page/1 …
```
=> Avoid warnings after split of Kernel.Typespec into {Kernel,Code}.Typespec

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs
With this change, now we can create the following links:
<pre>
* [`for`](`for/1`)
* [`is_boolean`](`is_boolean/1`)
</pre>
Refs: #679
=> Autolinl Kernel functions and special forms with shorthands

README.md
Adding a reference to the ExDoc hex documentation
=> Adding a reference to the ExDoc hex documentation

test/ex_doc/formatter/epub/templates_test.exs, test/ex_doc/formatter/html/templates_test.exs
Refactoring template tests (under` test/**/templates_test.exs`).
Two things were done:
* Describe blocks were added - the tests starting with the same prefix were grouped, using describe blocks.
* The code is now formatted with the help of the code formatter.
Changes related to this [issue](https://github.com/elixir-lang/ex_doc/issues/868).
=> Refactor templates tests

lib/ex_doc/config.ex, lib/mix/tasks/docs.ex, test/mix/tasks/docs_test.exs
Allowing to exclude docs from umbrella app docs utilizing `ignored_apps: [your selected apps]`.
I also have created tests for umbrella projects and tests for this specific case.
This PR is related to this [issue](https://github.com/elixir-lang/ex_doc/issues/867).
=> Allow apps to be excluded from umbrella app docs

lib/ex_doc/formatter/html.ex
The HTML fortmater may now accept SVG format
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
First add the .svg logo file path to `logo:`, like `logo: "priv/static/images/logo.svg"`
Run `mix docs`, and go to output location
You may see that the is behaving as any png and jpg, but svg is lighter and scalable
=> Support SVG

mix.exs
Not sure this is useful, but I saw some warning and given that 1.7 is out it might be a good idea to force a modern version of `Earmark`.
=> Pushing Earmark dependency to 1.2.5

README.md, lib/ex_doc/markdown.ex, mix.lock
This includes the remaining references to devinus/markdown,
which was a hoedown dependency.
Built-in hoedown support was removed in 0.18.0 (56829970).
=> Remove stale references to hoedown

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs
Round 1 is here: [WIP] Autolink revamp #893
This PR doesn't change the API as requested by @josevalim in https://github.com/elixir-lang/ex_doc/pull/893#issuecomment-419695702
=> [WIP] Autolink revamp - Round 2

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs
Additionally, remove Autolink.project_doc/4
Closes #904
=> Rewrite Autolink tests to use project_doc/2

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs, test/ex_doc/formatter/html_test.exs, test/fixtures/README.md
=> Autolink mix tasks

lib/ex_doc/formatter/html/autolink.ex
=> Always expand Elixir lib dirs

lib/ex_doc/retriever.ex
`ExDoc.FunctionNode`'s `:id` is composed of the function name, a slash, and the function arity. For example: `name/0`.
`ExDoc.ModuleNode` is sorting the functions alphabetically based on that `:id`, but it doesn't take into account that `"/" >= "!" == true`. That means that `fetch!/2` is displayed before `fetch/2`.
This is a regression from previous docs (check order of `fetch` and `fetch!`): [Elixir v1.6 `Map`](https://hexdocs.pm/elixir/1.6/Map.html#fetch/2), [Elixir v1.7.3 `Map`](https://hexdocs.pm/elixir/Map.html#fetch!/2)
=> Sort function names alphabetically in the sidebar

lib/ex_doc/config.ex, lib/ex_doc/formatter/epub.ex, lib/ex_doc/formatter/html.ex, lib/ex_doc/formatter/html/autolink.ex, lib/mix/tasks/docs.ex, test/ex_doc/formatter/epub/templates_test.exs, test/ex_doc/formatter/epub_test.exs, test/ex_doc/formatter/html/autolink_test.exs, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/formatter/html_test.exs, test/fixtures/protocol.ex, test/fixtures/warnings.ex
This only works for project's docs so when e.g. `Foo.bar/0` from `foo` dependency doesn't exist we won't warn yet.
We also don't warn when parsing extras pages, this is useful for Elixir deprecations page when we reference functions that are deprecated.
=> Warn on undefined remote functions from project's docs

lib/ex_doc/formatter/html/templates/head_template.eex, lib/ex_doc/formatter/html/templates/redirect_template.eex, test/ex_doc/formatter/html_test.exs
=> Use em-dash for separation in page title

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs
The text set in a custom link was lost.
[this is `my` module](MyModule)
would have just been converted to
[`MyModule`](MyModule.html)
=> Fix custom links in Elixir modules

lib/ex_doc/formatter/html/templates/footer_template.eex, lib/ex_doc/formatter/html/templates/head_template.eex
Closes #961
Even an empty script (`<script></script>`) at the end of `<body>` can break anchor links in Chrome for some reason. Fortunately, we can move the script to HTML `<head>` with `async` tag, which should not cause rendering performance to suffer. We can safely do that because our javascript already makes sure to run after the DOM is ready by using jQuery's [ready](https://api.jquery.com/ready/) handler [here](https://github.com/elixir-lang/ex_doc/blob/7ff86d47a7982d72ee16ef26a93cba790a86b355/assets/js/app.js#L34).
=> Fix anchor links sometimes not working by moving js to HTML head

lib/ex_doc/retriever.ex, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/retriever_test.exs
Previously signature where typespecs didn't have an argument name,
were named starting with 0
time_zone_period_from_utc_iso_days(arg0, arg1)
time_zone_period_from_utc_iso_days(Calendar.iso_days(), Calendar.time_zone()) :: ...
this commit fixes the number starting from 1
=> Fix typespec arg number

lib/ex_doc/formatter/html/autolink.ex
WIP because I don't know what name to choose, 
the first argument is prefix, but `p` in `pmfa` stands for prefix as well.
=> WIP: Name args in Autolink.default_text/4 helper

lib/ex_doc/formatter/html/templates.ex, test/ex_doc/formatter/html/templates_test.exs
This PR ensures that the anchor id's generated by `link_headings/3` are always unique.
This is achieved by replacing the simple use of `Regex.replace/3` with `Regex.scan/2` and an `Enum.reduce/3`, which keeps track of id's that already occurred and adds a `-n` suffix to them.
#998 will be fixed when this is merged.
=> Ensure that link_headings/3 generates unique anchor id's

assets/js/night.js
Detects if the browser prefers a dark color scheme and switches to dark mode automatically. Needs testing.
Relevant APIs:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia
=> Detect if browser prefers night mode

lib/ex_doc/formatter/html/templates/detail_template.eex
=> Fix tag mismatch error

lib/ex_doc/formatter/epub/templates/nav_template.eex
Remove the parent level when there's no group defined.
Before:
After:
=> Fix epub toc without groups

lib/ex_doc/config.ex, lib/ex_doc/formatter/epub/templates/content_template.eex, lib/ex_doc/formatter/html/templates/head_template.eex, lib/mix/tasks/docs.ex, test/ex_doc/formatter/epub_test.exs, test/ex_doc/formatter/html_test.exs
=> Add support for :authors config

lib/ex_doc/formatter/html/templates/head_template.eex
There is a bug with Night Mode switching.
To reproduce:
1. Go to https://hexdocs.pm/elixir/Kernel.html
2. Switch Night Mode `ON`
3. Switch Night Mode `OFF`
4. Refresh the page
**CURRENT:** Night Mode stays ON.
**EXPECTED:** Night Mode stays switched ON.
Local storage value is a truthy string (ie. "false", "true"), not a boolean. `if(localStorage.getItem('night-mode'))` is always `true` if the key is present.
=> Fix Night Mode detection

.travis.yml
Since we do more checkings in the latest version, run it first.
We do the same for Elixir core.
=> Travis: Reverse sort Elixir versions in matrix

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs
This is a continuation of 098b99fcec956a55d3feeae47957ff76e5269d56
Related issue: #1036
=> Do not strip "Elixir." from text, in fully namespaced calls

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs
We introduce another clause (`link_type == :custom ->`) because we only
want to warn for _custom_ links if we didn't find a match, for regular
links if given local function does not exist it's ok, perhaps the docs
refer to function the user is supposed to implement themselves.
Closes #1059.
=> Warn on unavailable local functions

lib/ex_doc/formatter/epub.ex, lib/ex_doc/formatter/epub/templates.ex, lib/ex_doc/formatter/epub/templates/content_template.eex, lib/ex_doc/formatter/html/autolink.ex
The internal content files on the EPUB document must be XHTML and their
extension is `.xhtml`.
=> (epub): Fix broken links to typespecs

lib/ex_doc/formatter/html.ex, test/ex_doc/formatter/html_test.exs
This intends to fix #1076
Tests are passing on both, case-sensitive system (Arch Linux with ext4) and case-insensitive system (OSX with ... uhm, their FS). Also, a warning is now correctly displayed on OSX.
I adjusted the test to cover this case as well, however, it doesn't really prove much. Not sure if this suffices or if we have to think of some way to actually make this behaviour testable on any system. - I couldn't think of an easy way of simulating the case-insensitive behaviour on my work machine / the CI)
=> Make index redirect warning case-sensitive

README.md
I think it's important to have a link to the page with the full configuration, otherwise it is difficult to find because it isn't explicitly linked anywhere.
A relative link might be better, but since this is a plain markdown file I'm not aware of a method that would work.
=> Readme: Add link to main configuration listing

lib/mix/tasks/docs.ex
Follow up to my last pull request which implemented a new config option to make this easier; instead just document the existing options a bit more and leave it up to the developer to set the pattern directly.
=> fully document :source_url_pattern

.gitignore
As you are aware I need to build the escript in order to generate the docs for Earmark, while doing so I get a _dirty_ repo, maybe you want to merge this humble PR in order to avoid this?
Thx in advance
=> Ignore escript in .gitignore

assets/less/night/night.less
This is currently night mode:
And light mode:
And with this PR:
=> Remove extra night-mode padding in .hljs

lib/ex_doc/retriever.ex, test/ex_doc/retriever_test.exs, test/fixtures/behaviour.ex
Closes #1093
Additionally we fix a bug where we haven't been handling macrocallback.
=> Link to callback docs instead of copying them

lib/ex_doc/formatter/html/autolink.ex, test/ex_doc/formatter/html/autolink_test.exs
I found no regressions between:
(cd ex_doc && git checkout master               && mix && cd ../elixir && make docs && mv doc doc_master)
(cd ex_doc && git checkout wm-typespec-autolink && mix && cd ../elixir && make docs && mv doc doc_branch)
(cd elixir && git diff --color-words --no-index doc_master doc_branch)
and in fact it fixed some minor bugs too.
=> Simplify typespec autolinking

lib/ex_doc/markdown/earmark.ex
With https://github.com/elixir-lang/ex_doc/pull/1109 the Earmark
dependency was set to `~> 1.4`
Earmark 1.4 no longer supports plugins see (https://github.com/pragdave/earmark/blob/master/RELEASE.md#140-20190905)
so setting this option through `ex_doc` is not possible anymore.
=> Remove plugins from Earmark config options

assets/js/night.js
Currently when a user visits the page during the night (or rather when
`prefers-color-scheme` is `dark`), the page uses night mode.
This is great, but what's not so great is that it remembers this as a
user choice, and won't automactically change if the user visits the page
at a later time during the day (when `prefers-color-scheme` is `light`
or `no-preference`).
This makes it so that night mode is an explicit choice, which is still
remembered. But if the user turns off night mode it goes back to the
light colors, and if the user later visits the site during night time,
that will be picked up.
The reasoning here is that it's called night mode, which previously was
a opt-in, but the current code makes it set the preference on first
load, and never let's the user change that.
=> Rely on `prefers-color-scheme` w/o night mode set

bin/ex_doc
Addressing these warnings:
```
% make docs                                                                                     
==> ex_doc (elixir)
bin/elixir ../ex_doc/bin/ex_doc "Elixir" "1.11.0-dev" "lib/elixir/ebin" --main "Kernel" --source-url "https://github.com/elixir-lang/elixir" --source-ref "cc8093aad9b58f32a2300e31838434275ec3664a"  --output doc/elixir --canonical "https://hexdocs.pm/elixir/master/ " --homepage-url "https://elixir-lang.org/docs.html" --formatter "html" --config "lib/elixir/docs.exs"
warning: missing parentheses on call to System.get_env/0. Parentheses are always required on function calls without arguments
/Users/.../Projects/ex_doc/bin/ex_doc:2
warning: missing parentheses on call to System.argv/0. Parentheses are always required on function calls without …
```
=> Added parens in ex_doc script

lib/ex_doc/autolink.ex
This way we will attempt to parse less expressions, notably we wouldn't
parse `()` which warns:
iex> Code.string_to_quoted("()")
warning: invalid expression (). If you want to invoke or define a function, make sure there are no spaces between the function name and its arguments. If you wanted to pass an empty block, pass a value instead, such as a nil or an atom
nofile:1
=> Make autolinker module parser stricter

lib/ex_doc/formatter/html.ex, lib/ex_doc/formatter/html/templates.ex, test/ex_doc/formatter/html_test.exs, test/ex_doc/retriever_test.exs, test/fixtures/common_nesting_prefix_b_a.ex, test/fixtures/common_nesting_prefix_b_b_a.ex, test/fixtures/common_nesting_prefix_b_c.ex, test/fixtures/common_nesting_prefix_bar.ex, test/fixtures/common_nesting_prefix_foo.ex
Module nodes are ordered by `nested_context`. Thus, the sidebar does not show the same nested group multiple times.
closes #1123
=> Modules grouped by prefix

lib/ex_doc/autolink.ex, test/ex_doc/autolink_test.exs
This PR fixes a bug causing types with a trailing `!` to not be auto linked any more.
The reason for this is that the regular expression introduced with #1103 does not account for those.
Consequently this is fixed by adding `!?` (an optional `!`) to the `name_string` capturing group.
Relevant screenshots:
<details>
<summary>v0.21.2 - links</summary>
</details>
<details>
<summary>3dcab6dc1beb7f4e118a48ef3f6b30331f98347b (commit before #1103) - links</summary>
</details>
<details>
<summary>a14aea847ef750b620f3ae5baccc0225d4488646 (or #1103) - does not link</summary>
</details>
<details>
<summary>v0.21.3 - does not link </summary>
</details>
<details>
<summary>4bb9a6f25dd2e522122daa48829a3d455e7f766a (current master) - does not link</summary>
</details>
<details> …
=> Auto link types with a trailing !

lib/ex_doc/formatter/html.ex, lib/ex_doc/retriever.ex, test/ex_doc/formatter/html_test.exs, test/fixtures/common_nesting_prefix_c.ex
When using both `:nest_modules_by_prefix` and `:groups_for_modules` together, groups might be rendered more than once:
This is due to the modules getting sorted first by groups and then later in the html formatter again by nested_context and nested_title. (introduced in #1141)
Including these sort criteria where modules are initially sorted seems to fix this while not breaking #1123 again.
=> sort modules by group, nested_context, nested_title, id

lib/ex_doc/markdown/earmark.ex
Before this patch, we maintained an allowed list of tags and attributes.
The list was incomplete and crashed on e.g. `<ol start="2">`.
I believe we have two options:
1. Maintain a proper allowed list of tags & attributes, e.g. from
xhtml1-*.dtd in OTP.
2. Remove allowed list.
I chose option 2.
=> Fix procesing markdown

lib/ex_doc/refs.ex, lib/ex_doc/retriever.ex, lib/ex_doc/utils/code.ex, test/ex_doc/refs_test.exs
Closes #1149
On such filesystems we'd get:
iex> :code.get_object_code(Elixir)
{Elixir, <<70, 79, 82, , ...>>, '(...)/../lib/elixir/ebin/Elixir.beam'}
And so we're getting the beam file for the private `:elixir` module.
=> Fix chunk extraction for Elixir module on case-insensitive fs

lib/ex_doc/autolink.ex, lib/ex_doc/formatter/html.ex, lib/mix/tasks/docs.ex, mix.exs, test/ex_doc/autolink_test.exs, test/ex_doc/formatter/html_test.exs
Previously we were warning like this:
warning: documentation references function ExUnit.Case.__using__/1 but it doesn't exist or isn't public (parsing Kernel.use/2 docs)
Now, to be consistent with other Elixir warnings, we output:
warning: documentation references function ExUnit.Case.__using__/1 but it is undefined or private
lib/elixir/lib/kernel.ex: Kernel.use/2
We're also making a breaking change to
`:skip_undefined_reference_warnings_on`, previously we could give it the
generated id of an extra e.g.: `["compatibility-and-deprecations"]`, now
we'd give it the path instead:
`["lib/elixir/pages/compatibility-and-deprecations.md"]`.
=> Update undefined reference warning and :skip_undefined_reference_warnings_on option

lib/ex_doc/autolink.ex, lib/ex_doc/formatter/html.ex, test/ex_doc/autolink_test.exs, test/ex_doc/formatter/html_test.exs
Currently we simply display the line number of the beginning of the docs
if present (i.e.: line of `@moduledoc`, `@doc`, etc. We don't do it for
extras)
In the future, when Markdown engine will return line number in AST,
we'll make the warning even more accurate.
=> Display line numbers for undefined reference warnings

lib/mix/tasks/docs.ex
I think the new default was only updated on the command line option.
=> Fix documentation of defaults for :fromatters

README.md
I think as HTML + EPUB is default now, we should remove the mention of the formatters options completely in the README.
=> Fix documentation of formatters defaults in README.md

lib/ex_doc/markdown/earmark.ex, test/ex_doc/markdown/earmark_test.exs
Fixes https://github.com/elixir-lang/ex_doc/issues/1165 by ignoring the fourth element in the tuple
=> Ignore fourth element in Earmark ast

mix.exs
We depend on experimental AST support that may change in Earmark v1.5.0
so let's keep our requirement stricter for now and possibly loosen it up
again in the future.
=> Make earmark version requirement stricter

README.md
In the install section, the README has an outdated version of ex_doc. This pull request updates it.
=> Update README to contain current project version.

assets/less/sidebar.less
=> Fix text overflow in sidebar

lib/ex_doc/autolink.ex, test/ex_doc/autolink_test.exs
add support for local path markdown to be autolinked as html in documentation generated
(as in https://github.com/elixir-lang/ex_doc/issues/1186)
example `../subscriptions.md` autolinked as `subscriptions.html`:
=> Add support for path dependent markdown autolink

lib/ex_doc/autolink.ex, lib/ex_doc/formatter/html.ex, lib/mix/tasks/docs.ex, mix.exs, test/ex_doc/formatter/html_test.exs, test/fixtures/LICENSE, test/fixtures/PlainText.txt, test/fixtures/PlainTextFiles.md, test/fixtures/README.md
The files with no extension are considered to be plain text.
Additionally it adds LICENSE as an extra file.
=> Allow files with no extension in extra files

assets/js/versions.js
If the same file exists in the selected version, redirect to it. Otherwise, send the user to the root page.
(the video did not record the select box with the other version)
```
// VersionNodes used in the GIF.
var versionNodes = [
{
version: "v0.19.3",
url: "http://workstation/ex_docs/0.19.3"
},
{
version: "v0.22.1",
url: "http://workstation/ex_docs/"
}
]
```
This feature was discussed in #1033
=> Redirect to correct file when change version

lib/ex_doc/refs.ex, test/ex_doc/autolink_test.exs, test/ex_doc/refs_test.exs
Refs no longer store wether the ref is public or not,
but adds the concept of visibility, such as :public, :hidden, :undefined
=> Revamp Refs

lib/ex_doc/refs.ex, lib/ex_doc/retriever.ex, test/ex_doc/refs_test.exs
* a5e8b3b Update Refs to better handle callbacks and types
If the module does not have a docs chunk, we fall back to `module.behaviour_info(:callbacks)` and `Code.Typespec.fetch_types(module)`
* c6abc63 Don't load module chunk if module is already cached
=> Improve Refs callbacks/types handling and cache hits

lib/ex_doc/autolink.ex, test/ex_doc/autolink_test.exs
It was breaking HTML validation when function name had special HTML chars that
needs to be escaped. such as `<`
=> Escape escape signature.

lib/ex_doc/formatter/html/templates.ex
Similar to https://github.com/elixir-lang/ex_doc/pull/1226
This bug was preventing funcions with special chars in their names to be displayed in the sidebar,
such as Kernel.</2
=> Escape HTML special characters in HTML sidebar entries

lib/ex_doc/autolink.ex, test/ex_doc/autolink_test.exs
Such as the case of Kernel.//2
=> Fix autolinking of functions with / in name

lib/ex_doc/formatter/html/templates/detail_template.eex, lib/ex_doc/retriever.ex, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/retriever_test.exs, test/fixtures/overlapping_defaults.ex
Removes from the :default field in %ExDoc.FunctionNode,
the default functions that overlap functions defined elsewhere,
and therefore printing two HTML elements with the same ID, making it an invalid HTML page.
It takes into consideration the ordered the functions are showed up in the HTML.
With this commit, the HTML documentation for Elixir is valid HTML
according to https://github.com/svenkreiss/html5validator
=> Remove overlapping functions from defaults

lib/ex_doc/autolink.ex, test/ex_doc/autolink_test.exs
- Change Autolink.warn/maybe_warn functions so they keep the original string provided in the documentation.
- The messages are defined within the warn functions.
- Show original string in warns.
- Warn on custom links with missing Mix tasks.
- Warn on custom links with missing Modules.
- Do not use kind in warnings for type, callback, functions/macros.
=> Change Autolink.warn/maybe_warn functions so they keep the original string provided in the documentation

test/ex_doc/autolink_test.exs, test/ex_doc/refs_test.exs
Do not use String.Unicode module for testing,
which happens to be the heaviest module in the Elixir codebase.
=> Speed up slow tests

assets/README.md, mix.exs
Additionally it appends a slash to the assets folder in the npm commands.
=> Fix npm command instructions in README file

README.md, assets/README.md, assets/package.json, mix.exs
Aditionally, it makes `mix lint` not to format any Elixir code.
=> Add lint.fix task

lib/ex_doc/autolink.ex, test/ex_doc/autolink_test.exs
It wouldn't detect typespecs ending in ?
Plus a more specific regex is included for detecting the typespec name.
=> Fix regex for autolink typespecs

lib/ex_doc/formatter/html/search_items.ex, test/ex_doc/formatter/html_test.exs, test/fixtures/README.md
Fixes a bug when a heading has no content (such as in the CHANGELOG)
=> Deal with headings without contents in sidebar sections

assets/less/sidebar.less, assets/test/tooltips/hints-extraction.spec.js, lib/ex_doc/formatter/html/templates/api_reference_template.eex, lib/ex_doc/formatter/html/templates/module_template.eex, lib/ex_doc/formatter/html/templates/sidebar_template.eex, test/ex_doc/formatter/html/templates_test.exs
Previously the version number would be before Application name.
This affects the readability in screen readers
Additionally the version number in the sidebar is no longer a heading.
=> Reformat Application (version number)

assets/less/content/general.less, assets/test/tooltips/hints-extraction.spec.js, lib/ex_doc/formatter/epub/templates/module_template.eex, lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/formatter/html/templates/api_reference_template.eex, lib/ex_doc/formatter/html/templates/module_template.eex, lib/ex_doc/formatter/html/templates/search_template.eex, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/formatter/html_test.exs
It only holds the title inside the heading,
Everything else, such as links are moved our of the heading.
Everything is contained in a `<div class="section-heading"> `tag.
**A) original****
**A) fixed****
***************
**B) original**
**B) fixed**
***************
**C) original**
**C) fixed**
***************
**D) original**
**D) fixed**
***************
**E) original**
**E) fixed**
=> Accessibility: Restructure headings

assets/js/templates/sidebar-items.handlebars
Closes #1229 
Adds an arrow next to `Sections` which links out to the same place as `Top`
=> Fix Sections arrow

test/ex_doc/autolink_test.exs, test/ex_doc/cli_test.exs
It reverts the changes introduced in dd799164abacc28b8b54a46c2a21e567b001309e
and makes of a feature introduced in Elixir v1.10 that we can read concurrently from a
captured named device
=> Make tests that capture IO asyncronous

lib/ex_doc/formatter/html.ex, lib/mix/tasks/docs.ex, test/mix/tasks/docs_test.exs
refs #1278 
https://github.com/elixir-lang/ex_doc/commit/dd48441baf0caff94e61c32de366ead209f7d92d isn't enough as a bug fix. I implemented the rest.
I respected `normalize_deps`, so previously, the link URL did not include the version, but it does.
`` `Jason` `` becomes
- before:
- `https://hexdocs.pm/jason/Jason.html`
- after:
- `https://hexdocs.pm/jason/1.2.2/Jason.html`
=> Respect deps config in autolink

assets/js/templates/sidebar-items.handlebars
Fixes https://github.com/elixir-lang/ex_doc/issues/1283
=> Fix html escaping in the sidebar entries

lib/ex_doc/autolink.ex, lib/ex_doc/refs.ex, test/ex_doc/autolink_test.exs, test/ex_doc/refs_test.exs, test/mix/tasks/docs_test.exs
Update warning messages based on Ref's visibility    
Messages are more accurate now.
Deal with private types
This PR spawned from https://github.com/elixir-lang/ex_doc/pull/1205 tackling most of the issues addressed there.
=> Warning based on refs

lib/ex_doc/autolink.ex, test/ex_doc/autolink_test.exs
Fixes #1288.
Currently a URI with no host, but with the scheme part present (like `about:blank`) is treated as a file reference and results in a warning (`documentation references file "about:blank" but it does not exist`).
Checking that both host and scheme parts are absent should do the trick.
=> Fix autolink to handle URIs with arbitrary scheme part without warning

lib/ex_doc/autolink.ex, test/ex_doc/autolink_test.exs
When on a module page, a reference to the same module is autolinked as `#content`. Such URL depends on the context and in some cases may not work as desired. For instance, have a look at the `Kernel` section [here](https://hexdocs.pm/elixir/api-reference.html), as you can see the autolinked `Kernel` resolves to `api-reference.html#content`, rather than `Kernel.html#content`, because the URL doesn't actually contain any path.
=> Change autolink to return path rather than just hash for the current module

assets/less/content.less, assets/less/content/bottom-actions.less, assets/less/night/content.less, assets/less/night/content/bottom-actions.less, lib/ex_doc/formatter/html.ex, lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/formatter/html/templates/bottom_actions_template.eex, lib/ex_doc/formatter/html/templates/extra_template.eex, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/formatter/html_test.exs
An initial idea for #1295.
Currently this adds next/previous links at the end of every page from *extras*. I'm not sure if this makes much sense for modules/tasks, as those are rather not read linearly.
You can see the build preview [here](https://static.jonatanklosko.com/ex-doc/issue1295/initial/readme.html). Screenshots for the reference:
**Desktop**
**Mobile**
=> Add next/previous at the end of extra pages

bin/ex_doc
Following issue #1303: proposed changes to fix the `makeup_erlang` dependency in `bin/ex_doc`
=> Fix makeup_erlang dependency

.github/workflows/ci.yml
actions/setup-elixir by default uses OTP that was built for ubuntu
14.04. By specifying the `experimental-otp: true` flag, we'll force it
to use the builds that match the runner. Nowadays, the default runner is
20-04.
The experimental-otp: true will likely be the default option on
setup-actions so it's safe to use it.
This also happens to fix the recent test failures on OTP 23. Turns out,
ubuntu-14.04 builds have doc chunks like this:
$ curl -LO https://repo.hex.pm/builds/otp/ubuntu-14.04/OTP-23.0.2.tar.gz && tar xzf OTP-*.tar.gz
$ elixir -e '"OTP-23.0.2/lib/stdlib-3.13/doc/chunks/array.chunk" |> File.read!() |> :erlang.binary_to_term() |> IO.inspect()'
{:docs_v1, [file: 'array.erl', location: 0], :erlang, "application/erlang+html",
:hidden, %{otp_doc_vsn: {1, 0, 0}}, []}
ubuntu-20.04 has …
=> Use OTP builds matching the OS on CI

assets/js/autocomplete/autocomplete-list.js, assets/js/sidebar/sidebar-search.js
Fixes #1310.
I made it so that opening a suggestion in a new tab/window (using `Shift` or `Ctrl`) would keep the autocomplete list open, but otherwise it always gets closed. I also changed the `Enter` behavior to mimic clicking a link rather than submitting a form, because otherwise we always navigate to a new page, even if the URL leads to the same page.
So this should unify clicking on a suggestion and pressing `Enter` to work the same way.
You can see a preview [here](https://static.jonatanklosko.com/ex-doc/issue1310/initial/ExDoc.Markdown.html).
=> Fix search click behavior when a suggestion refers the current page

assets/js/autocomplete/autocomplete-list.js, assets/js/sidebar/sidebar-search.js
Follow up for #1311, see [this comment](https://github.com/elixir-lang/ex_doc/issues/1310#issuecomment-751409542).
We rely on the blur event for closing the autocomplete box, but sometimes we have to ignore this event in which case we may end up in a not-easily-closable state. I added a `setTimeout` ensuring that the search gets re-focused when the autocomplete box is still open. While this doesn't seem extremely elegant, I tried several other approaches and none was perfect.
@eksperimental please have a look [here](https://static.jonatanklosko.com/ex-doc/issue1310/followup/ExDoc.Markdown.html) and let me know if it works as expected.
=> Improve search input blur handling

lib/ex_doc/refs.ex, test/ex_doc/autolink_test.exs, test/ex_doc/refs_test.exs, test/support/with_without_module_doc.ex
It corrects the visibility of functions that start with an underscore and that no docs have been defined.
Closes https://github.com/elixir-lang/ex_doc/issues/1308
/cc @jonatanklosko
=> Reimplement ExDoc.Refs.visibility helper

lib/ex_doc/formatter/html.ex, test/ex_doc/formatter/html_test.exs
While creating documentation that contained `<i></i>` inside a `<span>` element, the formatter was not able to cope with this html. See the included test.
=> fix ast_to_html with empty elements

lib/ex_doc/retriever.ex, test/ex_doc/retriever_test.exs
Previously, we were simply ignoring non-Elixir modules. Now, that we
started hanlding Erlang modules, we should simply ignore modules that
don't happen to have chunks. Some examples:
iex> Code.fetch_docs :elixir
{:error, :chunk_not_found}
iex> Code.fetch_docs :dets_server
{:error, :chunk_not_found}
=> Don't raise when module has no docs chunks

lib/ex_doc/autolink.ex, test/ex_doc/autolink_test.exs
www.erlang.org/man redirects to the erlang.org/man
additionally the prefered links are with https
=> Update erlang.org/man URL

lib/ex_doc/doc_ast.ex, test/ex_doc/doc_ast_test.exs
=> Generating void elements correctly on `DocAST.to_string`

lib/ex_doc/doc_ast.ex, lib/ex_doc/retriever.ex
There was a mix of variable rebinding,
and naming everything doc/docs.
This commit adheres to the name definitions in the Code.fetch_docs/1 specs
https://hexdocs.pm/elixir/Code.html#fetch_docs/1
=> Rename doc variables

assets/less/sidebar.less
It looks like we moved the ellipsis usage to be more specific in 6650cf1176330af380855a896769bfbb4adaa2a2 and I think we need to expand the places where ellipsis are used. For example, the docs for ExUnit currently look like this:
So this change makes it look like this:
I think this provides better affordance to let users know that there is more to the title than just what they can see. It also may be worth considering removing the `overflow: hidden` to let the lines spill over and have the whole thing be visible, but this change works within the parameters of the current design.
=> Add ellipsis to more sections

lib/ex_doc/retriever.ex, test/ex_doc/retriever_test.exs
It deals with signature for remote types, such as in:
`@callback callback1(GenServer.options()) :: :ok
`
it generates the function signature
`callback1(options)`
while previously it would generate
`callback1(arg1)`
=> Deal with remote types in signatures

lib/ex_doc/doc_ast.ex, lib/ex_doc/formatter/html.ex, lib/ex_doc/language.ex, lib/ex_doc/language/elixir.ex, lib/ex_doc/language/erlang.ex, test/ex_doc/doc_ast_test.exs
- ExDoc.Language: Add highlight_info/0 callback
- ExDoc.DocAST: Turn `<pre>` into `<pre><code>` for erlang+html
=> Erlang syntax highlighting

README.md
Hopefully this will be made easier soon by tighter integration in rebar3/rebar3_hex.
=> Add "Using ExDoc with Erlang projects" to README

assets/less/content/footer.less, lib/ex_doc/cli.ex, lib/ex_doc/config.ex, lib/ex_doc/formatter/html.ex, lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/formatter/html/templates/extra_template.eex, lib/ex_doc/formatter/html/templates/footer_template.eex, lib/ex_doc/formatter/html/templates/module_template.eex, lib/ex_doc/formatter/html/templates/not_found_template.eex, lib/ex_doc/formatter/html/templates/search_template.eex, lib/mix/tasks/docs.ex
Demo:
https://user-images.githubusercontent.com/76071/129177854-22787c72-1077-431c-970e-b9ea2777c8b9.mov
Future work: (out of the scope of this PR)
1. Support Hex diff. Currently when linking to Hex diff, we need to include two versions to diff against. It would be nice to be able to provide just a single version, e.g.: https://diff.hex.pm/diff/decimal/2.0.0, and Hex diff would automatically pick the version immediately preceding that.
2. Support Hex private packages. We can already do that for packages themselves but let's wait for private packages support in Preview (https://github.com/hexpm/preview/issues/48) and possibly Diff (https://github.com/hexpm/diff/issues/74)
=> Add Hex package configuration and display "Find on Hex" footer links

lib/ex_doc/language.ex, lib/ex_doc/retriever.ex
E.g. LFE.
Following is a demo of the crash; it's a rebar3 project which uses the [`rebar3_lfe`plugin ](https://hex.pm/packages/rebar3_lfe) to seamlessly import LFE (there's no need to have it installed.) 
It's got mixed Erlang & LFE code and, following the fix, the generated API reference includes a page for the Erlang module but none for the LFE modules, as expected.
[ex_doc_crash.tar.gz](https://github.com/elixir-lang/ex_doc/files/7117512/ex_doc_crash.tar.gz)
The crash can be reproduced by invoking `./generate_docs.sh`, assuming `ex_doc` is available on $PATH. It's happening right here, due to the function argument being `:lfe`:
https://github.com/elixir-lang/ex_doc/blob/50155806bb00506a5e199a894a5d2a47c24165f0/lib/ex_doc/language.ex#L134-L135
I performed the smallest possible change, …
=> Don't crash upon doc chunks for unknown beam languages

assets/js/sidebar/sidebar-drawer.js
**Issue:** https://github.com/elixir-lang/ex_doc/issues/1339
Resolves the issue with the state of the sidebar forcefully changing when the screen size updates. 
Now, the sidebar will track the preference of the user. 
When the preference is closed --> the sidebar will remain closed on window resize
When the preference is open (or no_pref) --> the sidebar will toggle according to screen width on resize
=> fix(sidebar): track user pref for sidebar state

lib/ex_doc/language/erlang.ex
The dialyzer report on file erlang.ex in line 364 that
the variable visibility cannot be a :private because
typespec declared it as :hidden or :public or :undefined.
Fixes it by removing :private on visibility check in do_url
function.
=> Do not check :private on visibility in ExDoc.Language.Erlang.do_url

assets/js/search-page.js
By default, the Lunr language processor splits words by spaces, and trims
special characters. This works for most cases, but when searching for
functions such as `Enum.all?`, nothing was returned.
This commit splits functions by module name, function name, and arity.
By providing this custom processor, the default trimming is skipped in
this scenario.
Closes #1381
=> Tokenize function names on search

lib/ex_doc/markdown/earmark.ex
I have deprecated the `smartypants` option in `EarmarkParser` v1.4.17 as it is not used by `ex_doc` and
logically shall go into the renderer ([`Earmark` 1.4.18](https://github.com/pragdave/earmark/issues/438))
Therefore this PR.
However if for a reason foreign to my knowledge you think you want to use smartypants again at some point I can undeprecate. It is not what I'd prefer though ;)
=> Removed smartypants option alltogether

README.md
Follow up to https://github.com/livebook-dev/livebook/pull/676.
=> Document how to render Vega-Lite plots

assets/js/content.js, assets/js/entry/html.js, assets/js/handlebars/templates/settings-modal-body.handlebars, assets/js/night.js, assets/js/settings-store.js, assets/js/settings.js, assets/js/tooltips/tooltips.js, assets/less/content/general.less, assets/less/html.less, assets/less/settings.less, assets/less/tooltips.less, lib/ex_doc/formatter/html/templates/extra_template.eex, lib/ex_doc/formatter/html/templates/footer_template.eex
Closes #1428.
Adds a configuration option for Livebook badges to redirect directly to the given instance. Also moves night mode/tooltips toggles to the new modal.
https://user-images.githubusercontent.com/17034772/141323071-941488a7-e2ae-412b-bd3e-6b25afb38550.mp4
=> Introduce settings modal

assets/less/content/general.less, lib/ex_doc/formatter/html/templates/module_template.eex, lib/ex_doc/nodes.ex, lib/ex_doc/retriever.ex, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/retriever/elixir_test.exs, test/fixtures/compiled_with_docs.ex
As a follow-up to this issue #1419. This PR adds a possibility to specify additional module's annotations that will be displayed right next to `View Source` icon. It can help to distinguish between different kinds of modules e.g. private ones when we decide to include them in documentation for internal purposes but make it obvious that they are private. In the end the annotation can be whatever we want.
I didn't know if I was to regenerate build files but I guess it happens during deployment?
I decided to go with the following pattern:
```elixir
defmodule InternalModule do
@moduledoc """
This documentation is for internal purposes...
"""
@moduledoc annotations: :private
end
```
The example UI looks like this:
=> Added optional module annotations

README.md
Closes #1434.
@fhunleth please give it a try and let me know if it works for you.
FTR initially I tried a slightly simpler solution, which was to first replace all `<pre>` tags with `<div class="mermaid">` and then run the automatic rendering:
```js
document.addEventListener("DOMContentLoaded", function () {
for (const codeEl of document.querySelectorAll("pre code.mermaid")) {
const preEl = codeEl.parentElement;
const graphDefinition = codeEl.textContent;
const graphEl = document.createElement("div");
graphEl.classList.add("mermaid");
graphEl.textContent = graphDefinition;
preEl.insertAdjacentElement("afterend", graphEl);
preEl.remove();
}
mermaid.initialize({ startOnLoad: true });
});
```
Then I tried a more manual approach, which I included in this PR. The primary difference is when the …
=> Document how to render Mermaid graphs

assets/less/content.less, assets/less/epub.less, assets/less/night/content/general.less
=> add support for themed img

lib/ex_doc/formatter/html/templates.ex, test/ex_doc/formatter/html/templates_test.exs
Closes #1433
/cc @NickNeck
There is one issue though, is that `%Task{}` is not a function
=> Use Struct instead of __struct__/0 in sidebar

lib/ex_doc/formatter/epub/templates/head_template.eex, test/ex_doc/formatter/epub_test.exs
This PR fixes a bug where the head template for epub had elixir hard coded for the style sheet resulting in a crash if the proglang differed (i.e., erlang).
=> Use config.proglang in epub head template

assets/js/handlebars/templates/search-results.handlebars, lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/formatter/html/templates/extra_template.eex, lib/ex_doc/formatter/html/templates/module_template.eex, lib/ex_doc/formatter/html/templates/not_found_template.eex, lib/ex_doc/formatter/html/templates/search_template.eex, lib/ex_doc/formatter/html/templates/settings_button_template.eex
This adds the settings button on all pages, I'm not sure if this is the best approach since the button is defined in both `settings_button_template.eex` and `search-results.handlebars`.
=> Add settings button to all pages

assets/js/quick-switch.js
If we search for `Ecto` in the global search, `hex.pm` returns packages that matches `ecto`. The JavaScript filtering should also show those packages.
I also made an assumption that all `hex.pm` packages are lowercase so when you search `Ecto` and press `Enter`, it now redirects to [`https://hex.pm/ecto`](https://hexdocs.pm/ecto/) instead of a `404` error for https://hexdocs.pm/Ecto.
=> Add case insensitive quick switch search match

CHANGELOG.md
Looks like the most recent changelog entries have the wrong year. This fixes that.
=> 2021 -> 2022 for latest changes

assets/less/variables/common.less
This PR slightly lowers contrast on headings in night mode.
P.S.: Some of the colors in the less file are annotated (i.e. `gray 200`) but it’s not obvious where these names come from. `gray 100` in this PR is an interpolation.
Updated
=> Slightly lower contrast of headings in night mode

assets/less/sidebar.less
Added a custom scrollbar to the sidebar as mentioned in #1480 .
I tried to avoid adding new colors and used the existing ones, but I am not sure if the hover color in Chrome is the best choice.
Since Firefox doesn't support changing the color on hover, it maybe would be better to make it static in Chrome as well?
Firefox:
Chrome:
Normal:
Hovered:
=> Add custom scrollbar for sidebar

assets/less/content/general.less
3rd level headers (are not properly aligned) with the text. The change adds missing left margin.
Example: https://hexdocs.pm/elixir/1.13.2/Kernel.SpecialForms.html#%3C%3C%3E%3E/1-options (compare "Options" and "Unit and Size")
=> Add missing margin for headers

mix.exs
It seems that the changelog link in the hex package info fell out of date.
=> Update changelog link

lib/mix/tasks/docs.ex
If start.exe is given multiple arguments, the first argument is the
window title. If the path contains spaces, e.g.
`c:/Users/John Doe/foo/index`, the stuff before the space would be
incorrectly interpreted as the window title.
=> Fix `mix docs --open` on Windows

assets/js/copy-button.js, assets/js/handlebars/templates/settings-modal-body.handlebars, assets/less/content/bottom-actions.less, assets/less/content/code.less, assets/less/makeup.less, assets/less/night/content/bottom-actions.less, assets/less/night/content/footer.less, lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/formatter/html/templates/sidebar_template.eex, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/formatter/html_test.exs
This PR solves some accessibility issues without modifying any behavior and with minor visual changes.
Light theme - More contrast for inline links and light grays
Dark theme - More contrast for footer text
=> Accessibility - general improvement 

assets/js/tooltips/hints.js, assets/test/tooltips/hints.spec.js
ExDoc puts the `<button>` for settings and the `<a>` to view source in front of the `<span>` containing the actual module name:
```html
<h1>
<button class="settings display-settings">
<i class="ri-settings-3-line"></i>
<span class="sr-only">Settings</span>
</button>
<a href="https://github.com/elixir-lang/elixir/blob/v1.13.2/lib/elixir/lib/gen_server.ex#L1" title="View Source" class="view-source" rel="help">
<i class="ri-code-s-slash-line" aria-hidden="true"></i>
<span class="sr-only">View Source</span>
</a>
<span translate="no">GenServer</span> <small>behaviour</small>
<small class="app-vsn" translate="no">(Elixir v1.13.2)</small>
</h1>
```
This resulted in a wrong heading for the tooltips. I changed the selector to `'h1 > span'` so it doesn't look into the `<a>` and `<button>` anymore.
=> Fix module hint heading extraction

lib/ex_doc/language/elixir.ex, test/ex_doc/formatter/html/erlang_test.exs, test/ex_doc/language/elixir_test.exs, test/ex_doc/language/erlang_test.exs, test/ex_doc/retriever/erlang_test.exs, test/test_helper.exs
=> Add `:otp_eep48` and `:otp_has_docs` tags

assets/js/search-page.js
Fixes underscore search by adding the `elixirTokenFunction` to the `searchPipeline` so search terms are processed before querying the index. Although this will also matches on tokens without an underscore, so `assert_` will also match `assert`, I'm not sure if this is ideal, but it seems like the best option I could find.
Ref: #1490
=> Add tokenizer to search pipeline

lib/ex_doc/retriever.ex, lib/ex_doc/utils/natural_order.ex, test/ex_doc/retriever_test.exs
Closes https://github.com/elixir-lang/ex_doc/issues/1440
=> Sort items "naturally" in menu, summary, function list, etc.

lib/ex_doc/retriever.ex
When generating docs for a list of paths rather than a single one, sorting was being done per-path rather than over the entire list of modules to include.
=> fix sorting when a list of dirs was provided

lib/ex_doc/formatter/html.ex, lib/ex_doc/retriever.ex, lib/ex_doc/utils.ex, test/ex_doc/retriever/source_pattern_test.exs
👋 Having a use case of generating one set of docs for a project + some of its dependencies, this allows providing a function instead of a single pattern, so we can link to the source within each dep's repo.
Always open to suggestions about how else I could go about this...
=> support for `source_url_pattern` in config being a function

README.md, assets/less/content/functions.less, assets/less/night/content/functions.less, lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/formatter/html/templates/detail_template.eex, lib/ex_doc/language.ex, lib/ex_doc/language/elixir.ex, lib/ex_doc/language/erlang.ex, test/ex_doc/formatter/html/erlang_test.exs, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/retriever/erlang_test.exs
See issue #602.
As well as replacing the heading I removed the padding as it seemed excessive, but I'm happy to restore that if you like.
Original:
New (without padding):
--
With padding:
--
=> Replace Specs heading

assets/js/entry/html.js, assets/js/handlebars/templates/settings-modal-body.handlebars, assets/js/keyboard-shortcuts.js, assets/js/night.js, assets/js/settings-store.js, assets/js/settings.js, assets/js/theme.js, assets/less/content.less, assets/less/makeup.less, assets/less/night/content.less, assets/less/night/keyboard-shortcuts.less, assets/less/night/night.less, assets/less/night/quick-switch.less, assets/less/night/search.less, assets/less/night/sidebar.less, assets/less/night/tooltips.less, assets/less/settings.less, lib/ex_doc/formatter/html/templates/head_template.eex
Currently, if you have set nightMode to true, there's not a way to go back and use the OS system default. Turning nightMode off will set it to false (not null). There's a hidden third setting of null that a user can't back to without clearing their localStorage.
Instead of a boolean nightMode (dark or not), change it to a 'theme' setting. The new themes are 'dark' and 'light' and 'system'. 'system' will allow for the user's OS to apply nightMode automatically depending on their system settings. Null and 'system' are treated as the same. 'dark' and 'light' will ignore OS settings. This keeps backwards-compatibility from older settings. The themes themselves are unchanged, however I did change verbiage from "night mode" to "dark mode"; there's technically a difference-- night mode is …
=> Change from nightMode to theme

lib/ex_doc/formatter/html/assets.ex
Not sure if `*.txt` is to ambitious, otherwise something like below could be a better solution.
```elixir
dist_license(), do: embed_pattern("dist/*.LICENSE.txt")
```
Ref: #1552
=> Include Javascript Script libraries in doc build

lib/ex_doc/formatter/html/templates/footer_template.eex, test/ex_doc/formatter/html/templates_test.exs
Show the "Built with" footer by `:proglang` option.
Fix task in https://github.com/elixir-lang/ex_doc/issues/1333
=> Show programming language in HTML footer

lib/ex_doc/language/elixir.ex, test/ex_doc/language/elixir_test.exs
I noticed that the link to `Kernel.SpecialForms.%/2` in [defstruct/1 doc](https://hexdocs.pm/elixir/Kernel.html#defstruct/1) was broken, this PR should fix it to point to https://hexdocs.pm/elixir/Kernel.SpecialForms.html#%25/2.
=> Escape &%/2 special form

test/ex_doc_test.exs, test/mix/tasks/docs_test.exs
Use tmp_dir in tests to avoid CI failures:
https://github.com/elixir-lang/ex_doc/runs/6293776556?check_suite_focus=true
=> Avoid race conditions in tests

assets/js/search-page.js
I noticed that lunr throws an error when it tries to load the serialized index from the `sessionStorage`. This causes the index to be generated upon each new search entry, which can have a performance impact for large projects.
Lunr throws the error because `elixirTokenSplitter` added to the pipeline during the index creation but it isn't registered when the index is loaded from the `sessionStorage`.
The following error is thrown when searching:
```
Failed to load index:  Error: Cannot load unregistered function: elixirTokenSplitter
```
=> Fix loading serialized index from sessionStorage

assets/js/search-page.js
Replaces default trimmer with custom trimmer to allow `@` at the beginning of a word.
Example:
Ref #1578
=> Implement custom trimmer to index `@` in search

assets/js/search-page.js
This is a proposal fix for #1588. Hyphens now are found by the index and get a higher score. 
These 2 lunr issues are relevant to understand the fix:
* https://github.com/olivernn/lunr.js/issues/296
* https://github.com/olivernn/lunr.js/issues/493
Some remarks about the solution:
* I've exported a `__createIndex` functions to be able to test it (`createIndex` uses globals)
* I've used the `searchNodes` from the live view docs, which is overkill and can be changed, but before I did, I wanted to make sure that this is the direction you want.
* I've got no idea on how to build/setup a version of ex_doc and test on the real docs to see how it actually works. If that's something I can easily do, let me know and I'll try it. (so I don't know if I broke anything...)
* I tried to maintain the …
=> fix for #1588

lib/ex_doc/language/elixir.ex, test/ex_doc/retriever/elixir_test.exs
related: #755 and #756
ping @josevalim
=> fix: remove extra term() argument at start of macrocallback spec

assets/css/content/admonition.css
While navigating on `ex_unit` using Hex, I found some styling issues when using inline code inside admonition header blocks. Check the bottom of [this page](https://hexdocs.pm/ex_unit/1.14.0/ExUnit.CaseTemplate.html#using/2) **using dark mode.** Not sure if it was added when adding support to admonition (#1400) or while removing less (#1597).
The problem happened when using inline code in admonition headers for some specific combinations, like the light theme and "errors" or the night theme and "warnings". Which would make the code to be too unreadable (gray font for the white background).
I'm following the same pattern for inline code that shows up in the admonition body, forcing the inline code tag color to be black. Examples of cases happening before and after the change above:
---
I'm …
=> fix: prevent unreadable text when using inline code with admonition eaders

assets/css/custom-props/common.css, assets/css/custom-props/theme-dark.css
Hi, I think this color for yellow color can be warmer and readable in both dark mod and light mod
As you see, we can't read the text in dark mod
---
Changing the color and format is based on the taste of each person.
**I did not separate the colors because a variable was created only for the color yellow.**
=> Readable yellow color for Dark mod

assets/css/content/code.css, assets/js/copy-button.js, lib/ex_doc/doc_ast.ex, lib/ex_doc/markdown/earmark.ex, test/ex_doc/markdown/earmark_test.exs
When rendering notebook contents with outputs, it is not obvious which blocks are outputs, especially that they are highlighted as regular code. This adds a specialized styling for output blocks.
=> Distinguish output code blocks

lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/language.ex, lib/ex_doc/language/elixir.ex, lib/ex_doc/nodes.ex, lib/ex_doc/retriever.ex
Hey folks! 🖖 
The types from `lib/ex_doc/nodes.ex` are outdated. 
This pull request updates these type definitions and fixes some issues Dialyzer found locally. 
I used a [small tool I made](https://github.com/antedeguemon/type_counselor) to automatically find the outdated types and revised them manually.
=> Fix broken types and some dialyzer issues

assets/js/sidebar/sidebar-drawer.js
Only restore close state.
Sidebar will still auto close on window resize.
As discussed in https://github.com/elixir-lang/ex_doc/pull/1606#issuecomment-1283887744.
=> Save sidebar state per session

lib/ex_doc/formatter/html.ex, lib/ex_doc/language/erlang.ex, test/ex_doc/formatter/epub_test.exs, test/ex_doc/language/erlang_test.exs
This change supports generating extras with Erlang syntax. Inline-code blocks are parsed as Elixir but written as Erlang, so `:telemetry.execute/3` is correctly autolinked and re-written as `telemetry:execute/3`.
Connects https://github.com/elixir-lang/ex_doc/issues/1333
=> Support Erlang Extras

assets/js/handlebars/templates/sidebar-items.handlebars, lib/ex_doc/formatter/html/templates.ex, test/ex_doc/formatter/html/templates_test.exs
This commit adds a tooltip to the sidebar with the function signature. This improves UX when listing functions with same name but different arities. It also works for types, guards, and callbacks.
Closes #1614
=> Add tooltip to functions on sidebar

lib/ex_doc/language/erlang.ex, test/ex_doc/language/erlang_test.exs
Closes #1575 
This commit attempts to resolve a case where there are specs defined referring to a function called record/*
=> Add exception for functions called record/*

README.md, mix.exs
Hey there! 
The [coveralls](https://hex.pm/packages/coveralls) library was removed from ex_doc by 649c21e, but it was kept as the default coverage tool - which caused `mix test --cover` to fail. 😿 
This PR does two things:
1. Removes Coveralls leftovers from `mix.exs` - so `mix test --cover` works again
2. Removes old coveralls.io badge from README - the coverage is pretty outdated since the last build is from 2019
=> Remove Coveralls leftovers

assets/css/print.css
Hello!
I know there is quite a bit of work to be done for Cheatsheets to be viably printed but there is some low hanging fruit as far as printability goes for ExDoc as a whole.
There's a bit of dupl
I'm split on a few things as we can set CSS to force page breaks and cause codeblocks to shift to resist being split across multiple pages etc, but very interested in knowing what direction you'd like to head with `print.css`!
Currently there's a large `300px` gap on the left side. We can remove this spacing as well as the Show Source and Settings buttons.
The background colors for admonition blocks disappear so we can make them visible again by bringing in borders.
The code blocks and inline code borders were a very low contrast which lets them disappear but also makes distinguishing them …
=> Initial pass at improving print.css

assets/css/_html.css, assets/css/content/cheatsheet.css, assets/css/print-cheatsheet.css, assets/css/print.css, lib/ex_doc/formatter/html/templates/head_template.eex
Hey hey! This attempts to make the printed version appear more like a low-ink version of the one column 1000px screen version of the Cheatsheet.
By wrapping all of the existing cheatsheet css in `@media screen` and adding a `@media print` section for the cheatsheet we have fewer styles to overwrite for printability. It halves the amount the columns displayed: `.list-4` displays 2, `.list-6` displays 3, etc. I've also brought back the Built using ExDoc portion of the footer string.
Styling for print could make further departures from the screen version for clarity but this is a large difference in usability from the existing print styles.
Two PDFs of the [ExDoc Cheatsheet](https://hexdocs.pm/ex_doc/cheatsheet.html) for comparison:
[Cheatsheet User Guide - …
=> Basic Cheatsheet print.css

assets/css/print-cheatsheet.css, assets/css/print.css
Hey hey!
Couldn't let this ship tomorrow without at least giving Firefox a look!
The markup looks fine so I can't quite give a good answer to why Firefox print renderer brings the H2's border down into the H3 in that one instance, but by using a `:before` pseudo element to add the border we remove the issue.
While I was there, I cleaned up the removal of the Print/Settings/View Source icons as two of them still rendered on print.
Additionally, I collapsed the borders on the code elements so there wouldn't be a double thick line when two code elements followed each other.
[Firefox Fixes.pdf](https://github.com/elixir-lang/ex_doc/files/10052605/firefox.fix.pdf)
When Firefox renders a PDF it handles `font-weight: 700` oddly and effectively just doubles the text and shifts it slightly?
Looks …
=> Firefox H2 print rendering fix

lib/ex_doc/config.ex, lib/ex_doc/retriever.ex, test/ex_doc/retriever_test.exs
This PR adds the possibility to specify additional function annotations that will be rendered by ExDoc. This is at the function level what https://github.com/elixir-lang/ex_doc/pull/1430 does for modules.
My use case is that a bunch of functions are generated at compile time and I want to mark them as such using ```@doc tags: [:generated]```
This would be the result:
=> Add optional function annotations

README.md, assets/README.md, assets/build/build.js, assets/package.json
To help with working on the assets.
When in watch mode, docs are rebuilt after each assets rebuild. I've used [mix commands](https://github.com/elixir-lang/ex_doc/pull/1632/files#diff-bcfc80f32c23faeb609b83289a81441e9c957c11adf7e9ddaef23e7647cf2d69R152-R153), triggered with `child_process.execSync()`. I now wonder if we can detect whether Mix or Rebar is in use and alter the commands as necessary to support both?
HTML and ePub rebuilds are done independently of each other, depending on which assets are changed.
A browser/ePub reader refresh/reload is currently still required, but at least we no longer have to run the `mix build` command for every iteration. Perhaps a mean of auto-refreshing the browser could be added later.
=> Add watch mode to asset build process

assets/css/content/cheatsheet.css, mix.exs
Hi there!
I happened to be browsing some of the new [Ecto cheatsheets](https://hexdocs.pm/ecto/associations.html) on my phone and noticed a couple of things:
- H3s were not wrapping, but instead extending off of the edge of the page
- General excess of whitespace which contributed to some unnecessary/strange wrapping and horizontal scrolling
Decided to take a crack at improving these things slightly and this PR is the result!
---
This PR introduces two CSS variables scoped to `.page-cheatmd`, `--horizontal-space` and `--vertical-space`, defined based on the common usage throughout the stylesheet, and then provides tighter spacing for screens under 600px wide (only chosen because that breakpoint was already being used elsewhere in the file).
It additionally decreases the vertical spacing …
=> Tighten up cheatsheet spacing on small screens and fix h3 line wrapping

assets/css/content/functions.css, assets/js/handlebars/templates/tooltip-body.handlebars
Fixes #1639 
Result screen for light theme:
And for dark:
=> Change format for tooltip header

lib/ex_doc/formatter/epub/templates/media-types.txt
This fixes an error when creating epub docs when an assets directory
contains `.license` files. These files are used to specify license and
copyright information to binary files like JPEGs and PNGs. See the
the [REUSE Specification](https://reuse.software) for an example that
documents the use of these files.
=> Add media type for .license files for epub

assets/css/content/cheatsheet.css, assets/css/content/code.css
Reference: #1643 
It might be worth leaving this open until other people have been able to provide feedback, in which case this can just be a catch-all for related fixes.
Link to review live mobile styles: https://hexdocs.pm/elixir/master/Kernel.html
=> Fix issues introduced by "Use more horizontal space on smaller screens"

assets/css/layout.css
The issue was showing up on the cheatsheet example page.
=> Prevent content-inner overflow (unwanted horizontal scrolling)

assets/css/sidebar.css
This annoyed me already too often, so I finally fixed it 😜 Basically it expands the `<a>` tag of the sidebar tabs instead of the `<li>` tag, so the clickable area is bigger and easier to hit.
=> Fix clickable area of sidebar tabs

assets/css/content/cheatsheet.css, assets/css/layout.css
Further to https://github.com/elixir-lang/ex_doc/pull/1650, this addresses the cause of the unwanted horizontal scrollbar on cheatsheet pages.
The offending element was the horizontal rule added to `h3`, which in some situations extended outside the containing column, and sometimes into/behind the next column.
Because a means of limiting the width of the rule (which is `::after` content) and achieving a consistent gradient between different headings isn't apparent to me, I've replaced the gradient with a solid colour and hidden the overflow of the `h3`. I've removed the `overflow-x: hidden` of the `.content-inner` `div` from the last PR on this, as that is no longer necessary.
Before:
After:
=> Prevent h3 horizontal rule causing horizontal page overflow/scrollbar

assets/css/content/cheatsheet.css, assets/css/print-cheatsheet.css, assets/css/print.css
Webkit browsers have supported break- properties for a good while.
=> Update print page break-related declarations

assets/css/content/cheatsheet.css, assets/css/print-cheatsheet.css
- Reduces use of “magic numbers” by using calc()
- Reduces number of selector blocks, avoiding repetition
- Removes units from 0 values
=> Tweak cheatsheet CSS

assets/css/custom-props/_erlang.css
`common.css` is imported from `_html.css` and `_epub.css`.
=> Remove superfluous import of common custom properties from Erlang CSS

assets/css/content/cheatsheet.css, assets/css/print-cheatsheet.css
Main changes:
- all background color removed in order to avoid potential photocopying issues;
- more color from the main styles' text preserved in order to keep more character;
- H3 horizontal rules preserved, at 2px instead of 1px to differentiate from 1px tables and code boxes;
- paragraphs' and lists' borders removed, and tables' left/right borders removed, in order to lessen the "boxiness" (this allows for the H3 rules to make more visual sense).
The "screen" media query is removed from the main cheatsheet styles, allowing them to apply to the printed version in order to reduce repetition of setting font, color, etc.
Increases use of .content-inner selector namespace to be safe.
The horizontal rules next to H3 text are achieved via background, and so only appear when the 'print …
=> Update Cheatsheet print styles

assets/css/content/admonition.css
Visited link styles were not being overridden by blockquotes, which caused visited links to appear with very low contrast.
Before:
After:
=> Fix visited link color in admonition blocks

assets/css/custom-props/theme-dark.css, assets/css/custom-props/theme-light.css, assets/css/sidebar.css
This is just the semantic naming changes of #1672 which should make it simpler for people to override styling to their preferences using browser plugins like Stylus. As far as I know, this will not result in any user-visible changes in either light or dark mode, but will give a user a clean list of CSS variables to tweak specifically for the sidebar.
=> Make sidebar CSS use semantic vars (attempt #2)

assets/css/_html.css, assets/css/settings.css, assets/css/sidebar.css, assets/js/entry/html.js, assets/js/os.js
Fixes #1675
As the sidebar type is thinned in Mac OS via the alternative anti-aliasing, its weight can be increased from light to normal to avoid overly thin type in Linux and Windows.
The thin weight is preserved/used in places where differentiation from normal/bold is warranted.
Additionally, the normal/400 weight font was not being loaded, which resulted in type set to normal being rendered light. We're now loading light/300, normal/400 and bold/700 for the Lato sans serif font.
All Firefox/Ubuntu, before followed by after. (@josevalim to make sure he's happy with Safari/WebKit in Mac OS.)
(Same as light theme sidebar.)
=> Improve consistency of type rendering weight across OSes

lib/ex_doc/cli.ex, test/ex_doc/cli_test.exs
Currently config takes precedence over switches. This was discussed in build and packaging working group and it was concluded this is unexpected behaviour. This PR rectifies that.
=> Fix precedence of switches vs config

README.md, assets/css/content/general.css, lib/ex_doc/nodes.ex, lib/ex_doc/retriever.ex, test/ex_doc/retriever/elixir_test.exs
`:since` was showing for functions, types, and callbacks, but not for modules.
=> Propagate :since metadata from modules

lib/ex_doc/markdown/earmark.ex, test/ex_doc/markdown/earmark_test.exs
Currently we are omitting the information if the output code block contains special content like mermaid graph.
=> Keep language class on livebook output code block

assets/css/content/general.css
Settings icon (on `readme.html`) was a little bit up.
Before:
After:
=> Fix settings icon position

assets/js/handlebars/templates/tooltip-body.handlebars, assets/js/tooltips/hints.js, assets/test/tooltips/hints.spec.js
=> Display tooltip content as html

README.md
Hi:
This commit just updates the ExDoc README for KaTeX.  The KaTeX version is bumped from 0.13.19 to 0.16.4 (latest), and a couple of additional things are added to the config. The KaTeX fonts are loaded, a plugin which lets you copy/paste TeX from the rendered browser page was added ([to see how it works, see this web page](https://upupming.site/katex-copytex/)), and the minimal configuration for the auto-render plugin was added.
Thanks!
-- Greg
=> Update the README - bump KaTeX version from 0.13.19 to 0.16.4, and update KaTeX config

assets/css/content/bottom-actions.css, assets/css/content/cheatsheet.css, assets/css/content/code.css, assets/css/content/general.css, assets/css/custom-props/common.css, assets/css/keyboard-shortcuts.css, assets/css/modal.css, assets/css/sidebar.css
=> Introduce borderRadius CSS variable

assets/css/custom-props/theme-light.css
The light theme's gradient that shows at small viewport widths was using the dark theme's colors.
=> Fix sidebar button background gradient color

assets/css/sidebar.css
8e86d630 (Layout on apple-os and sidebar, 2023-03-29) resulted in subitem list items in the sidebar having 300 weight on non-Apple, I believe unintentionally. This reinstates their 400 weight for non-Apple. (Although this means top-level and second-level items are the same weight for non-Apple, I believe it was agreed the more readable font weight took priority.)
To avoid this second declaration of font-weight 400 for non-Apple, we could instead use !important for the first declaration, but this may result in specificity issues if the design were to include different weights in future.
Screenshots below are from Chrome, Ubuntu.
=> Reinstate heavier font-weight for sidebar list items for non-Apple

assets/css/sidebar.css
We replace the default grey browser placeholder with a dimmed accent color from existing CSS variable
Small change but it is visually more pleasing 😄 
**Before**
**After**
=> Improve sidebar search placeholder text hue

.github/workflows/ci.yml, lib/ex_doc/language.ex, mix.exs
On 1.15-dev I started seeing some test failures. It is because we detect
whether we're on recent enough OTP for docs chunks like this:
otp_eep48? = Code.ensure_loaded?(:edoc_doclet_chunks)
And it started returning false on 1.15-dev unless we add :edoc to extra
applications. We need xmerl too to use some of the edoc functions.
=> Start edoc & xmerl when running tests

lib/ex_doc/formatter/html.ex, test/ex_doc/formatter/html_test.exs
This pull request adds a check to disambiguate the id generated ids if any of them are duplicated.
This already solves the issue, but I still have the following questions:
- Can we try to generate the ids considering the full filepaths (maybe parent directory), so that we don't need to disambiguate them later?
- I think this is possible, but probably there will be edge cases
- I couldn't find any great way to test it, does someone have an idea?
- I've tried adding multiple extra README.md files to the fixture `foo` app and then capturing IO/mix output, no success
- Are there any safe heuristics we could follow in order to avoid having `readme-1`, `readme-2`, etc in the URLs? Maybe using the groups or file paths?
Closes #1550
=> Allow multiple extra files with the same name

lib/ex_doc/formatter/epub.ex, lib/ex_doc/formatter/html.ex, test/ex_doc/formatter/epub_test.exs, test/ex_doc/formatter/html/erlang_test.exs, test/ex_doc/formatter/html/search_items_test.exs, test/ex_doc/formatter/html_test.exs, test/test_helper.exs
This pull requests adds a safety check before running `Fille.rm_rf!` when creating docs.
Now it will only allow users to select as output either:
- Unexisting directories (which will be created by ex_doc)
- Directories already managed by ex_doc (have the `.ex_doc` file)
One I think inevitable outcome of this is that this is a breaking change, users with existing `docs` folders that try to run it in a new version will receive the error message.
Maybe we can add a line in the error saying `Run "rm -rf docs" if you are seeing this after upgrading ex_doc`
Closes #1555
=> Safety check before running File.rm_rf! in doc gen

assets/css/autocomplete.css, assets/js/autocomplete/suggestions.js, assets/js/handlebars/templates/autocomplete-suggestions.handlebars, lib/ex_doc/formatter/html/templates.ex, test/ex_doc/formatter/html/templates_test.exs
This patch shows a `(deprecated)` tag when autocompleting deprecated nodes.
Preview:
Closes #1268
=> Distinct deprecated autocomplete suggestions

lib/ex_doc/language/elixir.ex, test/ex_doc/language/elixir_test.exs
This pull request adds a check to warn and remove a link if it is a reference (has backticks) and could not be parsed as a reference.
That means links such as  ``[supervisor docs](`t:supervisor.child_spec/0`)`` will now warn on build and not emit a broken link rather than failing silently.j
Closes #1572
=> Warn on invalid references in links

lib/ex_doc/utils.ex, test/ex_doc/formatter/html/search_items_test.exs
Inspect implementation for String is such that:
iex> ~S"#{}"
"\#{}"
However `\#` is invalid JSON escape code.
=> Fix escaping `#{}` in search_items.json

assets/js/search-page.js, lib/ex_doc/formatter/html.ex, lib/ex_doc/formatter/html/search_data.ex, lib/ex_doc/formatter/html/templates/search_template.eex, test/ex_doc/formatter/html/search_data_test.exs, test/ex_doc/formatter/html/templates_test.exs
- Rename `searchNodes` to `searchData`
- Add content-type based on proglang
=> Rename `searchNodes` to `searchData`

lib/ex_doc/formatter/html/search_data.ex, test/ex_doc/formatter/html/search_data_test.exs
Scholar can now persist its index after removing the vega-lite codeblocks
Partially fixes #1732 
Before trimming a section, we add a step to match vegalite codeblocks and remove them.
=> Ignore vegalite codeblocks in search

README.md
The Node version is documented in the CI config and the assets directory readme.
---
Sorry I missed this in the last PR.
=> Remove (out of date) Node version from main readme

assets/js/content.js
Some HTTP servers redirect and omit the `.html` extension when you go to an html page, hosting a generated doc on one of these makes the “Run in Livebook” button break because it doesn’t add the `.livemd` extension to the link. This PR fixes it making the `.html` optional in the replacement.
=> Fix generation of `.livemd` paths to handle omitted '.html'

lib/ex_doc/formatter/html/search_data.ex, test/ex_doc/formatter/html/erlang_test.exs
Recent changes around cleaning html and striping tags introduced a regression when it comes to generating ex doc for erlang modules.
Specifically, undocumented functions (exported or not) end up as a `nil` node in the ast. The nil node gets passed from 
[SearchData.node_child/2](https://github.com/elixir-lang/ex_doc/blob/main/lib/ex_doc/formatter/html/search_data.ex#L75) to [SearchData.extract_sections/2](https://github.com/elixir-lang/ex_doc/blob/main/lib/ex_doc/formatter/html/search_data.ex#L75), then to [SearchData.clean_html/1](https://github.com/elixir-lang/ex_doc/blob/main/lib/ex_doc/formatter/html/search_data.ex#L144). Said `ni`l node will cause a crash since `HTML.strip_tags/2` in has a binary guard clause. 
Since `strip_tags/2` has a guard clause the best place to catch this …
=> Adjust extract_sections/2 to account for undocumented erlang functions

assets/css/custom-props/theme-dark.css, assets/css/custom-props/theme-light.css, assets/css/sidebar.css, lib/ex_doc/formatter/html/templates/sidebar_template.eex
When I checked out the project to work on something else, I noticed an invalid CSS variable, `var(gray800-opacity-0)` (missing leading `--` in front of the name).
After digging around, I realized that, if fixed, the sidebar gradient would be a gradient from gray800 to gray800-opacity-0, and it would be rendered inside of the sidebar that already has a solid background color of gray800. That means the gradient would not be visible at all. Its positioning styles also mean that the gradient element never took up any space.
I decided it makes no sense to fix this gradient element that would be invisible anyway and doesn't affect the flow of other elements, and instead I'm deleting it.
=> Remove sidebar gradient

assets/css/content/admonition.css, assets/css/content/general.css, lib/ex_doc/formatter/html/templates.ex, test/ex_doc/formatter/epub/templates_test.exs, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/formatter/html_test.exs
Fixes https://github.com/elixir-lang/ex_doc/commit/28bb43e4bb2c20c7111524be34ed9100e1bfefab#r125061077
Also makes the link underline color the same as the text (usinig `currentColor`, which is black or white) for admonition headings.
=> Revert hover link approach to fix markup of headings containing links

lib/ex_doc.ex, lib/ex_doc/autolink.ex, lib/ex_doc/formatter/epub.ex, lib/ex_doc/formatter/html.ex, lib/ex_doc/language/elixir.ex, lib/ex_doc/nodes.ex, lib/ex_doc/retriever.ex, test/ex_doc/formatter/epub/templates_test.exs, test/ex_doc/formatter/html/search_data_test.exs, test/ex_doc/formatter/html/templates_test.exs, test/ex_doc/language/elixir_test.exs, test/ex_doc/retriever/elixir_test.exs, test/ex_doc/retriever/erlang_test.exs, test/ex_doc/retriever_test.exs, test/ex_doc_test.exs
This PR updates the retriever to also return a list of filtered modules, and updates the code to warn if we find a typespec that references a type from a filtered module.
Closes #1744
=> Warn if typespec references filtered module

lib/ex_doc/formatter/epub/templates/module_template.eex, test/ex_doc/formatter/epub/templates_test.exs
As discussed [here](https://github.com/elixir-lang/ex_doc/pull/1752#issuecomment-1713397635).
=> Remove links from module page self-pointing “hover link” headings in EPUB

assets/css/copy-button.css, assets/css/sidebar.css, assets/js/copy-button.js, assets/js/handlebars/templates/modal-layout.handlebars, assets/js/handlebars/templates/sidebar-items.handlebars, assets/js/handlebars/templates/versions-dropdown.handlebars, assets/js/sidebar/sidebar-drawer.js, assets/js/sidebar/sidebar-list.js, lib/ex_doc/formatter/html/templates/footer_template.eex, lib/ex_doc/formatter/html/templates/sidebar_template.eex, test/ex_doc/formatter/html/templates_test.exs
Resolves #1756
Task list:
- Missing landmark elements: `<nav>`, `<main>` ✅  https://github.com/elixir-lang/ex_doc/pull/1760/commits/c9d58cebf349a372f7cf9982b8c5f757ef391518
- Expand menu button is missing `aria-controls` and `aria-expanded` properties  ✅ https://github.com/elixir-lang/ex_doc/pull/1760/commits/132ccb2b7563c365ae67224ffafe1830e9d448b0
- Search input: `<p>` is not a valid child of `<label>`  ✅ https://github.com/elixir-lang/ex_doc/pull/1760/commits/17adec572f5d5d35206f8ee2bfd403991fe0e0f4
- Version select:
- Lacks a label.  ✅ https://github.com/elixir-lang/ex_doc/pull/1760/commits/86194b2d47f9c8d9c90922db7b62674a97885c45
- Decorative character "\25bc" in version select is being read as "down pointing black pointer".  ✅ …
=> Screen reader accessibility

lib/ex_doc/language/erlang.ex, test/ex_doc/formatter/html/erlang_test.exs
This PR is in reference to and resolves https://github.com/starbelly/rebar3_ex_doc/issues/66
=> Autolink support for handling remote types in records

assets/css/_epub.css, assets/css/content/epub-admonition.css, assets/js/content.js, assets/js/entry/epub.js
Create a custom style for admonition blocks for EPUB output, partially addresses https://github.com/elixir-lang/ex_doc/issues/1074
The comparison below was made using Apple Books
=> Admonition EPUB styles

lib/ex_doc/autolink.ex, lib/ex_doc/language/elixir.ex, lib/ex_doc/language/erlang.ex, test/ex_doc/language/erlang_test.exs
While 9579ce8 (from #1617) added features to `ex_doc`, it also stopped using hardcoded language `Elixir`, which seems to have had the unintended consequence of removing other features, like:
* the ability to report on invalid links (e.g. `warning: documentation references file "examples" but it does not exist`), and
* auto-linking from `.md` to `.html` (links aren't "transformed"), e.g. as per using `rebar3_ex_doc`.
I found the commit by `git bisect`'ing, and it helped me understand where the origin of the issue was.
This pr is just an initial step as I understand you might not want the Erlang handler calling the Elixir handler, but:
1. I don't know where to put the "generic" code,
3. I don't know if it's acceptable to simply copy the code over.
I did copy the tests over from the Elixir …
=> Restore warning on missing references and `.html` link (for `.md`)

assets/css/search-bar.css
This PR fixes an issue where the settings cog gets partially hidden under the search bar at certain sizes.
I've just added a `row-gap` between the search-bar and settings cog which seems to do the trick.  I feel there is some unnecessary CSS (which I will annotate) which doesn't seem to do anything, at least not once there is the gap.  I could be related to other browsers, of course.
I also removed some padding which seems to line up the cog with the code icon below a bit better, but I will undo that if requested (it's very subtle).
https://github.com/elixir-lang/ex_doc/assets/3752792/ce3c3142-9a3e-4294-b441-191821b5c07f
https://github.com/elixir-lang/ex_doc/assets/3752792/2e81abaf-e0ca-43c3-913c-829e53d03edf
=> Prevent search bar from overlapping settings cog

assets/css/custom-props/common.css, assets/css/layout.css, assets/css/sidebar.css
This is the result of discussion in #1799.
Make section tabs more tab-like, connecting the tabs to their content.  Ideally this will draw more attention to the different sections as it seems new users sometimes have trouble finding the guides.
Here's a screencap:
=> Redesign sidebar tabs

lib/ex_doc/autolink.ex, test/ex_doc/formatter/html_test.exs, test/ex_doc/language/elixir_test.exs
=> Use IO.warn for autolink warnings

.github/workflows/release.yml, .github/workflows/release_pre_built/action.yml
~Just cheking if I am on the right path here for [this one](https://github.com/elixir-lang/ex_doc/issues/1810) @josevalim.~
1. **`release.yml`**:
- Checks for the existence of a release corresponding to the pushed tag.
- Creates a new release if it does not already exist.
- Deploys pre-built binaries for different OTP versions.
- Supports OTP versions 24, 25, and 26, with placeholders for future versions.
2. **`release_pre_built/action.yml`**:
- Configurable for different major and minor OTP versions.
- Utilizes `erlef/setup-beam@v1.16.0` for setting up the Elixir environment.
- Generates SHA1 and SHA256 checksums for the built binaries.
closes #1810
=> Build precompiled ExDoc scripts on every release

.github/workflows/ci.yml, lib/ex_doc/autolink.ex, lib/ex_doc/language/elixir.ex, lib/ex_doc/retriever.ex, mix.exs, mix.lock, test/ex_doc/formatter/html_test.exs, test/ex_doc/language/elixir_test.exs, test/fixtures/warnings.ex
=> More accurate autolink warnings line

assets/css/content/general.css, assets/css/custom-props/theme-dark.css, assets/css/custom-props/theme-light.css
It looks like they were attempted to be added, but weren't rendering due to missing `border-collapse: collapse` on the table.
So now there are borders for both light and dark mode:
**After**:
=> Add borders dividing table rows in rendered content

lib/ex_doc/autolink.ex, lib/ex_doc/formatter/html.ex, lib/ex_doc/language/elixir.ex, lib/ex_doc/language/erlang.ex, test/ex_doc/language/erlang_test.exs
This PR does 3 things:
1. Change Erlang+Elixir autolinking to parse function links using specialized code instead of sharing. There are too many incompatible overlaps between the languages to make it possible to use the same parser for both.
2. Use correct line numbers for regular links, just as #1807 did for Elixir
3. Make Erlang docs warn when an unkown type or callback is used in regular links.
I'm a bit unsure about the last one, why is it that ExDoc Elixir does not warn for these?
```
`t:Bad:type/0`
```
Seems like there is very little chance of a false positive, and if there is one you can always silence it.
=> Fix Erlang Scanning & Warnings 

assets/css/autocomplete.css, assets/js/autocomplete/autocomplete-list.js, assets/js/search-bar.js, lib/ex_doc/formatter/html/templates/sidebar_template.eex
Allows navigation with <kbd>ctrl</kbd>+<kbd>n/p</kbd> on macOS and automatically scrolls the list so that the focused item is always visible.
=> Improve search bar navigation

lib/ex_doc/markdown/earmark.ex, mix.exs, mix.lock, test/ex_doc/markdown/earmark_test.exs
Closes #1571. Depends on https://github.com/RobertDober/earmark_parser/pull/142.
With this change we parse math expressions in Markdown and then rewrite them back to `$` and `$$`. Rendering the expressions is still up to the user, but this way we don't parse the expression contents as Markdown.
=> Do not parse math expressions as markdown

lib/ex_doc/autolink.ex, lib/ex_doc/language/erlang.ex, test/ex_doc/language/erlang_test.exs
Since I had not written proper tests for module anchors for Erlang, @wojtekmach's [fix for module anchors in Elixir](https://github.com/elixir-lang/ex_doc/commit/d2cbfb45299a436c818c76c50ab4a523a52be669) broke the support in Erlang.
So here is a PR with proper tests and working Erlang anchors.
=> Fix module anchors

assets/css/sidebar.css, lib/ex_doc/cli.ex, lib/ex_doc/formatter/html.ex, lib/mix/tasks/docs.ex, test/ex_doc/formatter/html_test.exs
Sets width and (auto) height of logo image.
Also allows for 'jpeg' filename extension to be used and updates docs.
Fix #1847
=> Fix SVG logo without width/height attrs not displaying

lib/ex_doc/formatter/epub/templates/content_template.eex, test/ex_doc/formatter/epub/templates_test.exs
We need to list all the resources included in the EPUB file in the OPF manifest, we missed doing that for the logo.
Basically this PR fix the following error found by `epubcheck`:
```json
{
"ID" : "RSC-008",
"severity" : "ERROR",
"message" : "Referenced resource \"OEBPS/assets/logo.png\" is not declared in the OPF manifest.",
"locations" : [ {
"path" : "OEBPS/title.xhtml",
"line" : 21,
"column" : 55
} ]
}
```
I also did some small refactor in this template.
=> epub: fix logo not declared in the OPF manifest

assets/css/custom-props/_elixir.css, assets/css/custom-props/_erlang.css, assets/css/custom-props/theme-dark.css, assets/css/custom-props/theme-light.css
Examples below. Please use thumbs up (you prefer blue) or down (you prefer the current) to state your preference.
=> Use blue links for Erlang

lib/ex_doc/autolink.ex, lib/ex_doc/config.ex, lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/formatter/html/templates/footer_template.eex, lib/ex_doc/retriever.ex, lib/ex_doc/utils.ex, lib/mix/tasks/docs.ex, test/ex_doc/formatter/html_test.exs, test/ex_doc/language/erlang_test.exs, test/ex_doc/retriever_test.exs
This PR does two things:
1. Adds `before_closing_footer_tag` config option for html formatter to insert a custom footer. We use it to insert a copyright notice at the end of each page.
2. Add kmfa to the metadata before calling `annotations_for_docs` so that the fun doing the processing knows which entry it is currently working with. We use this to classify functions/types into different categories, such as built-in/predefined.
and as a bonus it also adds a warning for when an `extra` that is not in deps is referenced in a link.
=> Add before_closing_footer_tag and adjust annotation metadata

assets/css/print.css
Noticed this when trying to print a cheatsheet, though it should apply to printing any documentation page as we cannot use it to search on paper / PDF :)
=> Hide search bar when printing

assets/css/content/admonition.css, assets/css/custom-props/common.css, assets/css/custom-props/theme-dark.css, test/examples/admonition.md
Admonition block heading backgrounds are set to the hues of the light theme and set to 80% opacity so as to mix with the background dark "gray" of the dark theme.
Admonition blocks‘ text, headings and links now rely on theme-specific custom properties.
As discussed in #1867
Mostly light tones for backgrounds.
Mix of light and dark tones for backgrounds. Potentially harsh on the eyes.
Mostly dark tones for backgrounds. Hopefully easier on the eyes and more consistent with the light theme.
=> Use dark backgrounds for admonition blocks in dark theme

lib/ex_doc/language/erlang.ex, lib/ex_doc/retriever.ex, lib/mix/tasks/docs.ex, test/ex_doc/retriever/erlang_test.exs
This PR adds `equiv` handling for types and callbacks to the Erlang mode by adding `doc_fallback` support to the retriever for types and callbacks. 
Also sneaking in a doc fix to describe keys available in metadata in `groups_for_*` functions.
=> Add `equiv` handling for types and callbacks for Erlang

Cheatsheet.cheatmd
Prompted by #1866 
I've tried to hint that not all features of ExDoc are intended to be used in cheatsheets without listing unsupported features with "which support a limited range of elements and formatting".
I've also shortened and tweaked some other wording in an attempt to simplify the experience of reading through and increase accuracy/relevance.
=> Update Cheatsheet guide wording

lib/ex_doc/autolink.ex, lib/ex_doc/config.ex, lib/ex_doc/language/erlang.ex, lib/mix/tasks/docs.ex, test/ex_doc/config_test.exs, test/ex_doc/language/elixir_test.exs
Currently, the `:skip_code_autolink_to` option only accepts a list.
This approach becomes impractical when dealing with a large number of terms.
For example, I'm working on a project where some hidden modules are automatically defined, and some documentation tries to link to those modules (to be precise, types defined in those modules).
My problem there is that the number of those terms is too many to list in `:skip_code_autolink_to` option.
So it is useful if `:skip_code_autolink_to` option accepts regular expressions or, more flexibly, a function.
I choose the function approach as it aligns with the discussion in https://github.com/elixir-lang/ex_doc/pull/1759#discussion_r1314751777.
(I'm pleased to implement the same feature for `:skip_undefined_reference_warnings_on` option if this PR …
=> Make a function acceptable for :skip_code_autolink_to option

lib/ex_doc/autolink.ex, lib/ex_doc/config.ex, lib/mix/tasks/docs.ex, test/ex_doc/config_test.exs, test/ex_doc/language/elixir_test.exs
In https://github.com/elixir-lang/ex_doc/pull/1878, `:skip_code_autolink_to` option has been updated to accept a function.
For consistency, the `:skip_undefined_reference_warnings_on` option should also be enhanced to accept a function.
=> Make a function acceptable for :skip_undefined_reference_warnings_on option

assets/css/layout.css, assets/css/search-bar.css, assets/js/helpers.js, assets/js/search-bar.js, lib/ex_doc/formatter/html/templates/sidebar_template.eex
This commit changes how the search bar is brought into view on desktop as brought up in #1860: when using one of the keyboard shortcuts to focus the input, the entire page jumps to the top making you lose your scroll position.  On mobile, technically smaller screens, this is remedied by causing the input to slide into view on scroll up, but I don't believe this is a desirable solution for desktop.
The following changes are introduced:
* Using one of the keyboard shortcuts will focus the search input causing it to stick to the top.
* It will continue to stick to the top so long as it is focused allowing you to scroll with it open.
* The slide-on-scroll effect has been changed to only fire on touch-enabled devices as opposed to just smaller screens.  This is allows us to make the hexdocs …
=> Bring search bar into view on desktop

lib/ex_doc/language/erlang.ex
Before this change a spec looking like this:
```
-spec foo(integer()) -> ok;
(atom()) -> ok.
```
would be transformed to:
```
-spec foo(integer()) -> ok;
(atom()) -> ok.
```
that is the second clause would be indented incorrectly.
=> Only remove -spec/-type from first line

lib/ex_doc/autolink.ex, test/ex_doc/language/elixir_test.exs
`mix ash_phoenix.gen.live` was not auto-linked, but it is now
=> fix: mix task regex didn't consider tasks with underscores

assets/js/modal.js
With many modals when you click outside the content the modal should close. This is helpful in the scenario where you press the 'g' keyboard shortcut and want to close it. The only way we can do so right now is by clicking the 'X' on the modal. I think this makes things more consistent with standard modal UI experiences and is a nice utility to have.
=> Allow the modal to close when we click outside the modal content

lib/ex_doc/autolink.ex, lib/ex_doc/language/erlang.ex, test/ex_doc/formatter/html/erlang_test.exs, test/ex_doc/language/elixir_test.exs, test/ex_doc/language/erlang_test.exs, test/ex_doc/retriever/erlang_test.exs
=> Use Hexdocs format in :otp anchors

lib/ex_doc/autolink.ex, test/ex_doc/formatter/html/erlang_test.exs, test/ex_doc/language/elixir_test.exs, test/ex_doc/language/erlang_test.exs, test/ex_doc/retriever/erlang_test.exs
This PR [continues](https://github.com/elixir-lang/ex_doc/pull/1908#issuecomment-2137138477) #1908 and replaces https://www.erlang.org/doc/man/ links with https://www.erlang.org/doc/apps/APP
=> replace OTP /man/ links with /apps/:app/

lib/ex_doc/formatter/html.ex, test/ex_doc/formatter/html_test.exs
I encountered this warning when upgrading and it wasn't immediately clear to me what I should do to fix it. This change updates the printed warning to show the exact valid config you could copy/paste into your `mix.exs`.
=> Give example when showing deprecation warning for binary assets config

assets/js/search-bar.js
Fixes #1913
Please note the removal of the code commented with "Add 'scroll-sticky' class when not at the top". This removal stops the search bar from appearing when a fragment identifier link is loaded, preventing the obscuring of content of linked-to sections, such as a heading. Is there any reason this code should stay?
=> Avoid unwanted showing/hiding of search bar on mobile when scrolling

assets/js/keyboard-shortcuts.js, assets/js/sidebar/sidebar-drawer.js, assets/js/sidebar/sidebar-version-select.js
When searching for docs in a search engine, the results don't always include the latest version as the first choice. This adds a `v` shortcut that will open the version select (if the user's browser supports it, otherwise it will focus it) to make selecting versions easier.
=> Adds a `v` shortcut to open/focus the version select

assets/css/search-bar.css
Previously, the `.search-input` set of styles defined `border: none`, while its `:focus` state has 1px border set. This led to the “micro-jump” of the placeholder text when the input field gets user focus (and it “jumps” back when it loses one).
With this simple fix, we always have an invisible 1px border set to the input, so it prevents “jumping”.
| Before | After |
|--------|-------|
| <video src="https://github.com/elixir-lang/ex_doc/assets/113878/5b74403e-7297-4564-b007-63cd29a58a0f"></video> | <video src="https://github.com/elixir-lang/ex_doc/assets/113878/3bf9c06e-14d8-4dd0-af79-262a1de20e14"></video> |
=> Fix search bar input on focus 1px shift

lib/ex_doc/autolink.ex, test/ex_doc/language/elixir_test.exs
Closes #1920
Took a spike at the feature I was talking about. Goes without saying, no worries if it's not something the maintainers are interested in =)
=> Allow anchors on function and callback autolinks.

assets/css/sidebar.css
I was browsing some docs earlier that used the `:nest_modules_by_prefix` config and found that, with a very long module list, it was very difficult to see the prefixes and almost impossible to quickly scan for (e.g. while scrolling down to find the next section).
This PR just adds 10px of margin above those prefixes, which is sufficient to visually set them apart. (10px is chosen because it's the same amount used when you expand a module subheader in the sidebar.)
=> Add top margin to nested module prefix in sidebar

lib/ex_doc/autolink.ex, test/ex_doc/language/elixir_test.exs
Closes #1932
When a module is hidden, its types will also be hidden. We check for two conditions and warn the user if both are met:
- The module defining the type is hidden
- The type itself is hidden If the type is undefined, the standard warning is displayed instead
It does not seem possible to do this check for Erlang modules.
=> Warn when trying to reference types in hidden modules

assets/css/content/admonition.css, assets/css/content/epub-admonition.css, assets/css/content/general.css, assets/css/print.css, assets/css/tabset.css, assets/js/content.js, assets/js/entry/epub.js, lib/ex_doc/markdown/earmark.ex, test/ex_doc/markdown/earmark_test.exs
Some screen readers will announce that an element is a blockquote. It could be potentially surprising to hear something announced as a blockquote despite the inner contents not being a quote.
References:
- https://adrianroselli.com/2023/07/blockquotes-in-screen-readers.html#Example01
- https://v5.chriskrycho.com/journal/psa-on-blockquotes/
Closes #1939
=> Convert admonition blockquotes to sections for screen reader users

README.md, lib/ex_doc/config.ex, lib/ex_doc/formatter/html.ex, mix.exs, test/ex_doc/formatter/html_test.exs
=> improvement: add `redirects` config, and documentation explaining it

assets/js/entry/html.js
=> Fix code copy buttons within tabsets

assets/js/search-page.js
In the LV repo you were not able to search for atoms inside backticks, for example when searching for "validate_attrs" the corresponding option of the `Phoenix.Component.slot/3` macro could not be found:
This commit fixes this by stripping the backticks from tokens and also removing trailing colons. I'm not familiar with the ex_doc codebase at all, so this may very well NOT be the way to properly fix, so please double check.
After this change:
cc @josevalim
=> allow searching for atoms inside backticks

lib/ex_doc/formatter/html.ex, lib/ex_doc/formatter/html/templates.ex, lib/ex_doc/retriever.ex, test/ex_doc/formatter/html_test.exs
This PR addresses issue [#1966](https://github.com/elixir-lang/ex_doc/issues/1966) by modifying the asset copying function to handle symbolic links correctly.
The commit [f4a46cb](https://github.com/elixir-lang/ex_doc/commit/f4a46cb0f8f11fbc9d8863a797b10afff1eefa31) changed the asset copying function from `File.copy/3` to `File.cp_r!/3`, which altered the handling of symbolic links.
To resolve this, we add the option `dereference_symlinks: true` to `File.cp_r!/3` as advised by José Valim.
- Ran `mix fix` to address linting issues present on the current `main` branch. If necessary, I can create a separate PR or revert this commit based on reviewer feedback.
- Passed `mix lint`
- Passed `mix test`
- Run `mix build` and check some pages in `doc/index.html`
- Confirmed that all assets are …
=> Copy symbolic links in the assets as actual files

lib/ex_doc/language/erlang.ex, test/ex_doc/retriever/erlang_test.exs
In cf49545 the pruning of edoc function was removed which causes more functions than there should be to be part of the generated docs.
This commit restores the old behaviour and adds a testcase.
=> Edoc still includes private functions so need to remove them

.gitignore, lib/ex_doc/cli.ex, lib/ex_doc/config.ex, lib/ex_doc/formatter/epub.ex, lib/ex_doc/formatter/html.ex, lib/ex_doc/utils.ex, lib/mix/tasks/docs.ex, test/ex_doc/formatter/epub_test.exs, test/ex_doc/formatter/html_test.exs, test/fixtures/single/lib/single.ex, test/fixtures/single/mix.exs, test/mix/tasks/docs_test.exs, test/test_helper.exs
Closes https://github.com/elixir-lang/ex_doc/issues/1411 https://github.com/elixir-lang/ex_doc/issues/1294
PR Originally published in #1412 #1564
=> Add --warnings-as-errors flag for non-zero exit code (Take 2)

assets/css/content/general.css
https://github.com/user-attachments/assets/dedb197e-fb52-44b9-9fa3-3e5626f314fe
> [!IMPORTANT]
> @josevalim, if you'd prefer the hover links to remain invisible until the heading is hovered/focussed, let me know and I'll revert that change.
Allows selection of heading text. Also makes hover link always (slightly) visible for discoverability.
Also improves:
- hover link colour
- hover link icon spacing
- heading spacing
Fixes #1969
=> Improve content headings

lib/ex_doc/language/erlang.ex, test/ex_doc/language/erlang_test.exs
@gomoripeti this is fixed in main but it will require Elixir v1.18+.
@garazdawi in the long term, we probably want the code that converts a typespec into a string with links to be part of Erlang/OTP? Perhaps by adding some sort of fallback to the existing pretty printing function? Or perhaps, instead of converting it to Elixir AST and traversing it, we'd traverse the Erlang AST typespec directly.
=> Fix typespec with (...) -> any(), closes #1974

mix.exs
This is the first version without warnings in Elixir 1.18.0
No other changes to the behavior.
=> Update mix.exs for EarmarkParser 1.4.42

assets/css/layout.css, assets/css/search-bar.css, assets/css/sidebar.css, assets/js/constants.js, assets/js/entry/html.js, assets/js/entry/inline_html.js, assets/js/sidebar/constants.js, assets/js/sidebar/sidebar-drawer.js, assets/js/theme.js, lib/ex_doc/formatter/html/templates/head_template.eex
Main improvement is reducing the layout shift caused by the sidebar popping in on page load.
* Set sidebar state & width in `inline_html.js`
* Reduce sidebar state & animation classes from 6 to 2
* Remove redundant body selectors
* Add max width to drawer
* Refactor `sidebar-drawer.js` to reduce indirection and simplify logic
* Register sidebar size observer on mousedown to avoid recording non-user changes and triggering DOM updates
* Simplify sidebar animation sequence reducing DOM updates and callbacks
* Refactor `theme.js`
* Remove toast on browser theme change (it made the code cleaner and I thought it was OK to go)
* Change script tags to [`defer`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#async_and_defer) - this removes the need for `onDocumentReady` helper …
=> Page load improvements

assets/css/content/functions.css, assets/css/content/general.css, lib/ex_doc/formatter/html/templates/detail_template.eex, lib/ex_doc/formatter/html/templates/extra_template.eex, lib/ex_doc/formatter/html/templates/module_template.eex, test/ex_doc/formatter/html_test.exs
@angelikatyborska, @josevalim,
This draft PR only updates the headings which contain action links:
- top-of-page headings;
- callback and function headings.
Headings which contain hover links are not changed here; the hover links do not include text so I believe "Navigated to ..." announcements are okay, and changing these headings would require some more styling updates. If it needs to be done I can look at doing so, but I thought I'd get you to take a look before spending more time on it.
@angelikatyborska, if you could take another look, that would be great.
Still to do:
- Checking callback/function annotations (e.g., 'macro'), which may be affected, though I'm hoping they will still be correctly aligned.
- Test updates.
I'll wait to hear back.
---
Avoids action link text being read …
=> Move action links out from heading tags

assets/js/sidebar/sidebar-drawer.js
Fixes https://github.com/elixir-lang/ex_doc/pull/2007#issuecomment-2580965575
Sorry, I put the init in the wrong update fn and didn't test.
I moved the init to the right fn, added a comment and renamed the wrong update fn to it's prev name before I changed it 🤦🏼‍♂️
Found another bug while testing. The close on content click didn't work after SWUP nav, the content element it was registered to is replaced on nav. Fixed by listening to body clicks.
=> Fix sidebar open/close on mobile

assets/css/custom-props/common.css, assets/css/custom-props/theme-dark.css, assets/css/custom-props/theme-light.css, assets/css/sidebar.css, assets/js/handlebars/templates/versions-dropdown.handlebars, assets/js/sidebar/sidebar-version-select.js
Continuation of #1918 *(could not push to the same branch since I'm not a maintainer)*
---
Based on feedback in #1918 here is the revised version of warning color and icon added when an outdated version is detected.
@halostatue I tried yellow but I could not make it work on Light mode. It would end-up look green-ish when lightness was reduced.
**NOTE**: Initially I wanted to put the icon after the version, but the `<select>` HTML element width is set to the largest possible item. This will create an unwanted padding that looks ugly in projects which have versions like `1.2.3-RC0`.
=> Add warning for stale version of documentation

assets/css/autocomplete.css, assets/css/content/cheatsheet.css, assets/css/content/code.css, assets/css/custom-props/theme-dark.css, assets/css/custom-props/theme-light.css, assets/css/sidebar.css
Introduce support for dark mode in the main scrollbar and enhance scrollbar styles to use native styles as much as possible for better contrast and more predictable scrollbars adhering more to user expectations.
=> Add main scrollbar dark mode support and improve scrollbar styles

assets/css/autocomplete.css, assets/css/content/admonition.css, assets/css/content/code.css, assets/css/copy-button.css, assets/css/custom-props/common.css, assets/css/search-bar.css, assets/css/settings.css, assets/css/toast.css, assets/css/tooltips.css
I noticed border radius inconsistencies so i addressed them via a single variable.
Update border-radius styles across various components to utilize a CSS variable, ensuring consistency in design. Adjust the variable value for improved appearance.
=> Refactor border-radius styles to use CSS variable for consistency

assets/css/copy-button.css, assets/js/copy-button.js, assets/js/handlebars/templates/copy-button.html
Replace the aria-live span with a success icon in the copy button, enhancing user feedback upon copying. Adjust button behavior to disable during the copy process and ensure the icon displays correctly when clicked.
https://github.com/user-attachments/assets/00d90d22-4002-41e9-b0ad-a6cd56fb2889
=> Refactor copy button to use success icon

assets/css/content/code.css
Improves the readability of inline code by adding word-wrap functionality.
before
after
=> Add word-wrap to inline code to fix overflow

assets/js/sidebar/sidebar-version-select.js
Base on [this comment](https://github.com/elixir-lang/ex_doc/pull/2012#discussion_r1910302119) from @wojtekmach (thank you), this PR adds redirect to exact page user currently is visiting in case it exists in the latest version.
P.S sorry for the delay. I was unwell for the past week.
=> Go to latest with path if exists

assets/css/autocomplete.css, assets/css/content/bottom-actions.css, assets/css/content/functions.css, assets/css/content/general.css, assets/css/copy-button.css, assets/css/custom-props/common.css, assets/css/modal.css, assets/css/search-bar.css, assets/css/search.css, assets/css/settings.css, assets/css/sidebar.css
Standardize transition properties by introducing a common variable, ensuring uniformity in animation effects throughout the styles.
https://github.com/user-attachments/assets/dc3e4223-bd72-4934-9344-cdaf6b4dcd91
https://github.com/user-attachments/assets/c2a2f162-487c-43e2-8e41-2057f4d64060
=> Refactor transitions for consistency across styles

assets/css/content/general.css
Adding block display and overflow properties to the table improves responsiveness and enhances the user experience on smaller screens.
bug
=> Make table responsive with block display and overflow properties

assets/css/content/general.css
Eliminate uppercase transformation for better readability and ensure content cells handle text without wrapping.
I couldn't find where the italic`em` is being applied so i can get rid of it
before
after
=> Remove uppercase transformation from table headers and add nowrap to content cells

assets/css/sidebar.css
Improve sidebar styles to handle overflow better and ensure text displays correctly without wrapping.
before
after
=> Enhance sidebar styles for overflow and text display

assets/css/content/functions.css, assets/css/custom-props/common.css
Refactor styles for deprecated content and update yellow color variables to enhance accessibility.
before
after
colors inspired by https://docusaurus.io/docs/markdown-features/admonitions
=> Refactor deprecated content styles and improve accessibility colors

assets/css/content/summary.css
Eliminate the italic font style in the summary synopsis to enhance text clarity and readability
research https://ux.stackexchange.com/a/62752
before
after
=> Remove italic font style from summary synopsis for improved readability

assets/css/content/general.css
Only allow td wrapping to avoid headers overflowing because of long td cells and having to horizontally scroll to see the rest of the headers.
before
after
=> Refactor table wrap for improved text handling

assets/css/custom-props/common.css
Improved visibility of option elements by adding a background color. this is because select transparency doesn't apply to option elements so it defaults to white which breaks in dark mode
before
after
=> Add background color to option elements for improved visibility

assets/css/content/general.css
Eliminate unnecessary top padding from the action icon to improve alignment in the top heading.
before
after
=> Fix code action icon position in top heading

assets/css/content/functions.css
Modify the margin-top for the icon action in the detail header to improve layout consistency.
before
after
=> Adjust margin-top for icon action in detail header

assets/css/_html.css, assets/package-lock.json, assets/package.json
Switch to modern-normalize for better cross-browser consistency in styling and remove the deprecated normalize.css.
tailwind uses modern-normalize https://v3.tailwindcss.com/docs/preflight
normalize.css hasn't been updated in 6 years
i've done some testing and everything looks the same as before
=> Replace normalize.css with modern-normalize for improved styling consistency

assets/css/content/general.css, assets/css/content/summary.css, assets/css/copy-button.css, assets/css/custom-props/common.css, assets/css/layout.css
Eliminate unused variables and redundant font family declarations to streamline the CSS files.
this pr introduces no visual changes but fixes font hierarchy because sansFontFamily which is meant for titles and the sidebar was being applied on the entire site and this fixes that so now we have proper font cascading behavior where the default font is actually the default
normalize already sets things globally https://github.com/sindresorhus/modern-normalize/blob/ba66c6fe35c7ae33954120c73e69d57de4249a0b/modern-normalize.css#L26
=> Fix font cascading behavior and clean up CSS by removing unused variables and redundant declarations

README.md, assets/js/content.js, assets/js/copy-button.js, assets/js/makeup.js, assets/js/quick-switch.js, assets/js/search-bar.js, assets/js/search-page.js, assets/js/settings.js, assets/js/sidebar/sidebar-drawer.js, assets/js/sidebar/sidebar-list.js, assets/js/swup.js, assets/js/tabsets.js, assets/js/tooltips/tooltips.js
=> Add exdoc:loaded event

assets/js/sidebar/sidebar-list.js, assets/js/swup.js
Re: https://github.com/elixir-lang/ex_doc/pull/2069#discussion_r1929493618
The sidebar-list is lazy-rendered so will always be called after the first `exdoc:loaded` event.
I re-arranged a few lines and added some comments to make it more obvious that it's not the standard `exdoc:loaded` -> `init()` pattern.
=> Remove remaining swup:page:view listeners

assets/css/content/general.css, assets/css/layout.css
Only `top-heading` headings are affected, and only when content is wider than 600px.
Callback/function headings have not been changed; they continue to always wrap so as to prioritise text display.
A container has been registered in the layout styles, meaning that we can easily conditionally apply styles based on the content width irrespective of whether or not the sidebar is shown.
https://github.com/user-attachments/assets/59fd72b6-de59-472c-9a64-753d18ea8778
=> Ensure top heading action icon is to right when width allows

assets/css/content/bottom-actions.css, assets/css/custom-props/theme-dark.css, assets/css/custom-props/theme-light.css
Adjust colors for bottom action buttons to improve visibility and consistency across dark and light themes.
=> Update bottom actions button colors for themes

.github/workflows/ci.yml, lib/ex_doc/language/elixir.ex, lib/ex_doc/language/erlang.ex, test/ex_doc/language/erlang_test.exs
Turns out that there actually was a test for this, but as the codepath was Elixir 1.18 only it was never tested in CI. So this PR adds Elixir 1.18 to the CI matrix and fixes the fun problem.
Fixes regression in #1980
=> Fix so that `fun()` in Erlang does not try to generate any link

assets/css/autocomplete.css, assets/css/content/admonition.css, assets/css/content/bottom-actions.css, assets/css/content/cheatsheet.css, assets/css/content/code.css, assets/css/content/functions.css, assets/css/content/general.css, assets/css/copy-button.css, assets/css/custom-props/common.css, assets/css/keyboard-shortcuts.css, assets/css/modal.css, assets/css/search-bar.css, assets/css/settings.css, assets/css/tabset.css, assets/css/toast.css, assets/css/tooltips.css
One reason for this suggestion is avoiding the optical mismatch between inner and outer frames:
This introduces an inner radius and an outer radius:
Summary:
- Most elements' border radii are reduced to 3px; nearer to what they were before, but still very slightly rounder if I'm not mistaken, and so not such a stark change.
- Tabset frames' border radius is increased to 12px.
- Admonitions being set to the 'inner', smaller radius is the biggest difference to the last release; here they are more square, despite, of course, not always appearing within another frame. I don't mind this, but thought it worth flagging.
<strike>This also introduces the inner/small radius to callback/function headings:</strike>
Draft status as there are likely more outers to change to inners. I'll wait to hear …
=> Improve tabset corners; rework border-radius across styles

assets/css/content/general.css
There was unwanted space between action icons when there were multiple icons.
=> Fix top-heading action icon spacing

assets/css/tabset.css
Increases margin of last element unless it's a `pre` (code box).
Left: before. Right: after.
=> Increase margin-bottom of last textual element in tabset content

README.md, lib/ex_doc/cli.ex, lib/ex_doc/config.ex, test/ex_doc/cli_test.exs, test/ex_doc/config_test.exs
While the `ExDoc` API already supports _umbrella projects_, the functionality is not exposed through the `ex_doc` CLI, making it hard to create sites for projects that include more than one application.
Here we propose a simple change, allowing users to specify multiple `ebin` directories when invoking `ex_doc`. If multiple `ebin` directories are specified and no custom `groups_per_modules` option is specified, we automatically group modules by application, which seems to be a sensible default.
Fixes #2071
=> Support for umbrella projects via CLI

lib/ex_doc/doc_ast.ex
Currently `` ```c++ `` is not highlighted, because `+` does not match `\w` in the regex. We could allow list `+`, but I relaxed the regex to pick up any class name.
=> Fix code highlighting for languages with non-alphanumeric characters

assets/js/sidebar/sidebar-drawer.js
I've been reading quite a few ExDoc sites from my mobile lately and I've found it slightly frustrating that clicking on some headings causes a full page change and the nav is closed, but within a module the sidebar stays open and it's unclear that you've even navigated
An example of the previous behaviour:
https://github.com/user-attachments/assets/b8e0090b-b1eb-4e5d-a101-4dd8bcb5c88a
=> Automatically close the sidebar when navigating sections on mobile

lib/mix/tasks/docs.ex
Currently there isn't any documentation about the requirement to push releases/tags to the `source_url` to get links to specific versions of the code. So this PR adds this documentation.
I couldn't find a general spot where `source_url` is talked about so I added an admonition near where it is first introduced.
Background: recently (in https://github.com/PostHog/posthog-elixir/pull/14#issuecomment-2778825519) I was asked where the requirement for pushing git tags comes from. I wasn't able to find any official documentation (here or in https://hexdocs.pm/elixir/writing-documentation.html) so I have created this PR.
Here's what it looks like when I build the documentation locally:
=> Document the requirement to push releases

lib/ex_doc/formatter/html.ex
Previously the generated `.build` file would contain these entries:
...
assets
assets/kv-observer.png
assets/logo.png
assets/logo.png
...
=> Remove duplicate entries and assets/ folder in .build file in HTML formatter
